Wizleap-Inc/wiz-ui

.github/workflows/deploy-storybook.yml
.github/workflows/deploy-vitest.yml
packages/wiz-ui/src/components/base/buttons/text/text.stories.ts
packages/wiz-ui/src/components/base/heading/heading.stories.ts
packages/wiz-ui/src/hooks/use-z-index.test.ts

ci: vitestのciエラーを修正

---

packages/constants/component/name.ts
packages/constants/styles/font-size.ts
packages/styles/bases/badge.css.ts
packages/styles/bases/header.css.ts
packages/styles/bases/icon.css.ts
packages/styles/commons/index.ts
packages/styles/commons/offset.css.ts
packages/wiz-ui/src/components/base/badge/badge.stories.ts
packages/wiz-ui/src/components/base/badge/badge.vue
packages/wiz-ui/src/components/base/badge/index.ts
packages/wiz-ui/src/components/base/icon/icon.stories.ts
packages/wiz-ui/src/components/base/icon/icon.vue
packages/wiz-ui/src/components/base/index.ts

Feat: WizBadge

---

packages/constants/styles/spacing.ts
packages/wiz-ui/src/components/base/tables/unstyled/table.stories.ts
packages/wiz-ui/src/components/base/tables/unstyled/table.vue

WizUnstyledTable: 双方向spacingに対応

---

packages/wiz-ui/src/components/base/inputs/index.ts

checkboxのexport忘れ

---

packages/constants/styles/spacing.ts
packages/wiz-ui/src/components/base/stack/stack.vue
packages/wiz-ui/src/components/base/tab/tab-pane.vue
packages/wiz-ui/src/components/base/tables/unstyled/table.vue
packages/wiz-ui/src/components/base/text/text.stories.ts
packages/wiz-ui/src/components/base/text/text.vue
packages/wiz-ui/src/components/custom/chat/card/chat-card.vue
packages/wiz-ui/src/components/custom/chat/item/chat-item.vue
packages/wiz-ui/src/components/custom/notification/panel/panel.vue

Fix: px py 入れ替えに対応、デザインのバグ修正

---

.github/workflows/visual-regression-test.yml
packages/wiz-ui/src/components/base/tables/unstyled/table.vue

WizUnstyledTableのborder-spacingのxyが逆

---

packages/wiz-ui/src/components/base/inputs/timepicker/time-picker.vue

resolve: #104 
- Timepicker で、「時」、「分」が追加されたので修正した。
- 一部 CSS を修正した

Timepicker で、「時」、「分」を追加

---

packages/styles/bases/calendar.css.ts
packages/styles/bases/stack.css.ts
packages/styles/bases/text-area.css.ts
packages/styles/bases/text.css.ts
packages/styles/bases/tooltip.css.ts
packages/styles/commons/gap.css.ts
packages/styles/commons/index.ts
packages/styles/commons/line-height.css.ts
packages/styles/commons/white-space.css.ts
packages/styles/customs/chat-card.css.ts
packages/wiz-ui/src/components/base/calendar/calendar.vue
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui/src/components/base/inputs/timepicker/time-picker.vue
packages/wiz-ui/src/components/base/stack/stack.vue
packages/wiz-ui/src/components/base/text/text.vue
packages/wiz-ui/src/components/base/textarea/text-area.vue
packages/wiz-ui/src/components/base/tooltip/tooltip.vue
packages/wiz-ui/src/components/custom/chat/card/chat-card.vue

refactor: vanilla extract式のスタイルに変更

---

packages/styles/bases/menu.css.ts
packages/wiz-ui/src/components/base/index.ts
packages/wiz-ui/src/components/base/menu/index.ts
packages/wiz-ui/src/components/base/menu/menu-item.stories.ts
packages/wiz-ui/src/components/base/menu/menu-item.vue

https://wizleap.slack.com/archives/C02VDE55431/p1672199976456799?thread_ts=1672196603.382819&cid=C02VDE55431 であげられたコンポーネントの実装
- Hover, Active, Disabled を追加
- click 機能の追加

Feature: WizMenuItem 

---

packages/wiz-ui-next/src/components/base/anchor/anchor.vue
packages/wiz-ui-next/src/components/base/avatar/avatar.vue
packages/wiz-ui-next/src/components/base/badge/badge.vue
packages/wiz-ui-next/src/components/base/box/box.vue
packages/wiz-ui-next/src/components/base/buttons/icon/icon.vue
packages/wiz-ui-next/src/components/base/buttons/text/text.vue
packages/wiz-ui-next/src/components/base/buttons/toggle/toggle.vue
packages/wiz-ui/src/components/base/anchor/anchor.vue
packages/wiz-ui/src/components/base/avatar/avatar.vue
packages/wiz-ui/src/components/base/badge/badge.vue
packages/wiz-ui/src/components/base/box/box.vue
packages/wiz-ui/src/components/base/buttons/icon/icon.vue
packages/wiz-ui/src/components/base/buttons/text/text.vue
packages/wiz-ui/src/components/base/buttons/toggle/toggle.vue

Props の型修正 (a ~ b) まで

---

packages/wiz-ui-next/src/components/base/tab/tab-pane.vue
packages/wiz-ui-next/src/components/base/tab/tab.vue
packages/wiz-ui-next/src/components/base/tag/tag.vue
packages/wiz-ui-next/src/components/base/text/text.vue
packages/wiz-ui-next/src/components/base/textarea/text-area.vue
packages/wiz-ui-next/src/components/base/tooltip/tooltip.vue
packages/wiz-ui/src/components/base/tab/tab-pane.vue
packages/wiz-ui/src/components/base/tab/tab.vue
packages/wiz-ui/src/components/base/tag/tag.vue
packages/wiz-ui/src/components/base/text/text.vue
packages/wiz-ui/src/components/base/textarea/text-area.vue
packages/wiz-ui/src/components/base/tooltip/tooltip.vue

Props の型修正（t (table を除く)）

---

packages/wiz-ui-next/src/components/base/inputs/base/base.vue
packages/wiz-ui-next/src/components/base/inputs/checkbox/checkbox.vue
packages/wiz-ui-next/src/components/base/inputs/datepicker/date-picker.vue
packages/wiz-ui-next/src/components/base/inputs/panel-switch/panel-switch.vue
packages/wiz-ui-next/src/components/base/inputs/password/password.vue
packages/wiz-ui-next/src/components/base/inputs/radio/radio.vue
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui-next/src/components/base/inputs/text/text.vue
packages/wiz-ui-next/src/components/base/inputs/timepicker/time-picker.vue
packages/wiz-ui-next/src/components/base/inputs/toggle-switch/toggle-switch.vue
packages/wiz-ui/src/components/base/inputs/base/base.vue
packages/wiz-ui/src/components/base/inputs/checkbox/checkbox.vue
packages/wiz-ui/src/components/base/inputs/datepicker/date-picker.vue
packages/wiz-ui/src/components/base/inputs/panel-switch/panel-switch.vue
packages/wiz-ui/src/components/base/inputs/password/password.vue
packages/wiz-ui/src/components/base/inputs/radio/radio.vue
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui/src/components/base/inputs/text/text.vue
packages/wiz-ui/src/components/base/inputs/timepicker/time-picker.vue
packages/wiz-ui/src/components/base/inputs/toggle-switch/toggle-switch.vue

Props の型定義の修正 (Input)

---

packages/wiz-ui-next/src/components/base/tables/card/th.vue
packages/wiz-ui-next/src/components/base/tables/flat/td.vue
packages/wiz-ui-next/src/components/base/tables/flat/th.vue
packages/wiz-ui-next/src/components/base/tables/unstyled/table.vue
packages/wiz-ui-next/src/components/base/tables/unstyled/td.vue
packages/wiz-ui-next/src/components/base/tables/unstyled/th.vue
packages/wiz-ui/src/components/base/tables/card/th.vue
packages/wiz-ui/src/components/base/tables/flat/td.vue
packages/wiz-ui/src/components/base/tables/flat/th.vue
packages/wiz-ui/src/components/base/tables/unstyled/table.vue
packages/wiz-ui/src/components/base/tables/unstyled/td.vue
packages/wiz-ui/src/components/base/tables/unstyled/th.vue

Props の型定義の修正 (table)

---

packages/wiz-ui-next/src/components/base/box/box.vue
packages/wiz-ui-next/src/components/custom/notification/list/list.vue
packages/wiz-ui/src/components/base/box/box.vue
packages/wiz-ui/src/components/custom/notification/list/list.vue

NotificationListのWizBoxのscrollの修正

---

packages/styles/bases/badge.css.ts
packages/wiz-ui-next/src/components/base/badge/badge.stories.ts
packages/wiz-ui/src/components/base/badge/badge.stories.ts

fix: Badgeのpointer eventsを外して子要素のクリックがきくように

---

.gitignore
package.json
packages/wiz-ui-next/vite.config.ts
packages/wiz-ui/vite.config.ts
yarn.lock

refactor: OptionAPIのバンドルを削除

---

packages/styles/bases/pagination.css.ts
packages/styles/bases/tab.css.ts
packages/wiz-ui-next/src/components/base/navigation/item.vue
packages/wiz-ui-next/src/components/base/pagination/pagination.stories.ts
packages/wiz-ui-next/src/components/base/pagination/pagination.vue
packages/wiz-ui/src/components/base/navigation/item.vue
packages/wiz-ui/src/components/base/pagination/pagination.stories.ts
packages/wiz-ui/src/components/base/pagination/pagination.vue

resolve: #265
resolve: #266
resolve: #267

Fix: tag / tab / navigation

---

packages/wiz-ui-next/src/components/base/box/box.vue
packages/wiz-ui/src/components/base/box/box.vue

fix:wiz-boxのpropsにmin/maxの設定を追加

---

packages/styles/bases/popup.css.ts
packages/styles/bases/tag.css.ts
packages/styles/commons/border-spacing.css.ts
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui-next/src/components/base/tag/tag.stories.ts
packages/wiz-ui-next/src/components/base/tag/tag.vue
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui/src/components/base/tag/tag.stories.ts
packages/wiz-ui/src/components/base/tag/tag.vue

resolve: #274
resolve: #271
resolve: #268
resolve: #264

Fix: selectbox table tag

---

packages/styles/bases/navigation.css.ts

fix:navigation-itemにcursor:pointer追加

---

packages/styles/bases/checkbox-input.css.ts

fix:checkboxのサイズ調整

---

packages/wiz-ui-next/src/components/base/avatar/avatar.stories.ts
packages/wiz-ui-next/src/components/base/badge/badge.stories.ts
packages/wiz-ui-next/src/components/base/buttons/icon/icon.stories.ts
packages/wiz-ui-next/src/components/base/buttons/text/text.stories.ts
packages/wiz-ui-next/src/components/base/buttons/toggle/toggle.stories.ts
packages/wiz-ui/src/components/base/avatar/avatar.stories.ts
packages/wiz-ui/src/components/base/badge/badge.stories.ts
packages/wiz-ui/src/components/base/buttons/icon/icon.stories.ts
packages/wiz-ui/src/components/base/buttons/text/text.stories.ts
packages/wiz-ui/src/components/base/buttons/toggle/toggle.stories.ts

Storybook のコンポーネントに Document を追加した(a~b)

ドキュメントの追加 (a~b)

---

packages/styles/bases/selectbox-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.stories.ts
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui-next/src/components/base/inputs/selectbox/types.ts
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.stories.ts
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui/src/components/base/inputs/selectbox/types.ts

feat(selectbox): optionの右側にvalueに含まれないlabelの追加

---

packages/styles/bases/card.css.ts
packages/styles/bases/tag.css.ts
packages/wiz-ui-next/src/components/base/card/card.stories.ts
packages/wiz-ui-next/src/components/base/card/card.vue
packages/wiz-ui-next/src/components/base/tag/tag.stories.ts
packages/wiz-ui-next/src/components/base/tag/tag.vue
packages/wiz-ui-next/src/components/custom/chat/card/chat-card.vue
packages/wiz-ui/src/components/base/badge/badge.stories.ts
packages/wiz-ui/src/components/base/card/card.stories.ts
packages/wiz-ui/src/components/base/card/card.vue
packages/wiz-ui/src/components/base/tag/tag.stories.ts
packages/wiz-ui/src/components/base/tag/tag.vue
packages/wiz-ui/src/components/custom/chat/card/chat-card.vue

fix: title/hint propsの廃止、汎用性を持たせるように

---

packages/styles/bases/pagination.css.ts
packages/wiz-ui-next/src/components/base/pagination/pagination.vue
packages/wiz-ui/src/components/base/pagination/pagination.vue

Fix: paginationのlength5未満の処理とPaginationガタガタ問題の修正

---

packages/wiz-ui-next/src/components/base/header/header.vue
packages/wiz-ui/src/components/base/header/header.vue

fix(header): z-indexをbaseLayerからfloating Layerに

---

packages/styles/bases/selectbox-input.css.ts

WizSelectBoxのlabelとexLabelの縦位置を揃える

---

packages/constants/component/name.ts
packages/styles/bases/circle-graph.css.ts
packages/wiz-ui-next/src/components/base/graphs/circle/bar.vue
packages/wiz-ui-next/src/components/base/graphs/circle/circle.stories.ts
packages/wiz-ui-next/src/components/base/graphs/circle/circle.vue
packages/wiz-ui-next/src/components/base/graphs/circle/index.ts
packages/wiz-ui-next/src/components/base/graphs/circle/types.ts
packages/wiz-ui-next/src/components/base/graphs/index.ts
packages/wiz-ui-next/src/components/base/index.ts
packages/wiz-ui/src/components/base/graphs/circle/bar.vue
packages/wiz-ui/src/components/base/graphs/circle/circle.stories.ts
packages/wiz-ui/src/components/base/graphs/circle/circle.vue
packages/wiz-ui/src/components/base/graphs/circle/index.ts
packages/wiz-ui/src/components/base/graphs/circle/types.ts
packages/wiz-ui/src/components/base/graphs/index.ts
packages/wiz-ui/src/components/base/index.ts

Feat: circle graph

---

packages/styles/bases/poll-graph.css.ts
packages/wiz-ui-next/src/components/base/graphs/index.ts
packages/wiz-ui-next/src/components/base/graphs/poll/bar.vue
packages/wiz-ui-next/src/components/base/graphs/poll/index.ts
packages/wiz-ui-next/src/components/base/graphs/poll/poll.stories.ts
packages/wiz-ui-next/src/components/base/graphs/poll/poll.vue
packages/wiz-ui-next/src/components/base/graphs/poll/row.vue
packages/wiz-ui-next/src/components/base/graphs/poll/types.ts
packages/wiz-ui/src/components/base/graphs/index.ts
packages/wiz-ui/src/components/base/graphs/poll/bar.vue
packages/wiz-ui/src/components/base/graphs/poll/index.ts
packages/wiz-ui/src/components/base/graphs/poll/poll.stories.ts
packages/wiz-ui/src/components/base/graphs/poll/poll.vue
packages/wiz-ui/src/components/base/graphs/poll/row.vue
packages/wiz-ui/src/components/base/graphs/poll/types.ts

Feat: poll graph

---

packages/styles/bases/transition-graph.css.ts
packages/wiz-ui-next/src/components/base/graphs/index.ts
packages/wiz-ui-next/src/components/base/graphs/poll/poll.stories.ts
packages/wiz-ui-next/src/components/base/graphs/transition/bar.vue
packages/wiz-ui-next/src/components/base/graphs/transition/container.vue
packages/wiz-ui-next/src/components/base/graphs/transition/index.ts
packages/wiz-ui-next/src/components/base/graphs/transition/transition.stories.ts
packages/wiz-ui-next/src/components/base/graphs/transition/transition.vue
packages/wiz-ui-next/src/components/base/graphs/transition/types.ts
packages/wiz-ui/src/components/base/graphs/index.ts
packages/wiz-ui/src/components/base/graphs/transition/bar.vue
packages/wiz-ui/src/components/base/graphs/transition/container.vue
packages/wiz-ui/src/components/base/graphs/transition/index.ts
packages/wiz-ui/src/components/base/graphs/transition/transition.stories.ts
packages/wiz-ui/src/components/base/graphs/transition/transition.vue
packages/wiz-ui/src/components/base/graphs/transition/types.ts

Feat: transition graph

---

packages/constants/component/name.ts
packages/styles/bases/meter-graph.css.ts
packages/styles/commons/background.css.ts
packages/wiz-ui-next/src/components/base/graphs/index.ts
packages/wiz-ui-next/src/components/base/graphs/meter/index.ts
packages/wiz-ui-next/src/components/base/graphs/meter/meter.stories.ts
packages/wiz-ui-next/src/components/base/graphs/meter/meter.vue
packages/wiz-ui-next/src/components/base/graphs/poll/poll.vue
packages/wiz-ui-next/src/components/base/graphs/transition/transition.vue
packages/wiz-ui/src/components/base/graphs/index.ts
packages/wiz-ui/src/components/base/graphs/meter/index.ts
packages/wiz-ui/src/components/base/graphs/meter/meter.stories.ts
packages/wiz-ui/src/components/base/graphs/meter/meter.vue
packages/wiz-ui/src/components/base/graphs/poll/poll.vue
packages/wiz-ui/src/components/base/graphs/transition/transition.vue

feat: meter graph

---

packages/styles/bases/selectbox-input.css.ts

fix: 日本語等の全角文字が入ったときにoverflowよりも改行が優先されてしまいellipsisされない問題を修正

---

packages/constants/component/name.ts
packages/styles/bases/line-graph.css.ts
packages/styles/bases/upload-display.css.ts
packages/wiz-ui-next/src/components/base/graphs/index.ts
packages/wiz-ui-next/src/components/base/graphs/line/index.ts
packages/wiz-ui-next/src/components/base/graphs/line/line.stories.ts
packages/wiz-ui-next/src/components/base/graphs/line/line.vue
packages/wiz-ui-next/src/components/base/inputs/upload/upload-display.vue
packages/wiz-ui/src/components/base/graphs/index.ts
packages/wiz-ui/src/components/base/graphs/line/index.ts
packages/wiz-ui/src/components/base/graphs/line/line.stories.ts
packages/wiz-ui/src/components/base/graphs/line/line.vue
packages/wiz-ui/src/components/base/inputs/upload/upload-display.vue

feat: seplate progress bar

---

packages/wiz-ui-next/src/components/base/inputs/checkbox/checkbox.stories.ts
packages/wiz-ui-next/src/components/base/inputs/checkbox/checkbox.vue
packages/wiz-ui-next/src/components/base/inputs/checkbox/types.ts
packages/wiz-ui-next/src/components/custom/form/group.stories.ts
packages/wiz-ui/src/components/base/inputs/checkbox/checkbox.stories.ts
packages/wiz-ui/src/components/base/inputs/checkbox/checkbox.vue
packages/wiz-ui/src/components/base/inputs/checkbox/types.ts
packages/wiz-ui/src/components/custom/form/group.stories.ts

ドキュメントの追加、checkboxのoptionsにkeyを追加
resolve: #324

ドキュメントの追加、checkboxのoptionsにkeyを追加

---

packages/styles/bases/tooltip.css.ts
packages/wiz-ui-next/src/components/base/tooltip/tooltip.stories.ts
packages/wiz-ui-next/src/components/base/tooltip/tooltip.vue
packages/wiz-ui/src/components/base/tooltip/tooltip.stories.ts
packages/wiz-ui/src/components/base/tooltip/tooltip.vue

feat: tooltipの位置を選択できるようにする機能の追加、リファクタリング

---

MIGRATION.md
packages/styles/bases/selectbox-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui-next/src/components/custom/chat/card/chat-card.stories.ts
packages/wiz-ui-next/src/components/custom/chat/card/chat-card.vue
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui/src/components/custom/chat/card/chat-card.stories.ts
packages/wiz-ui/src/components/custom/chat/card/chat-card.vue

Feat(WizChatCard): Chatの下部にSelect Boxを設置

---

packages/wiz-ui-next/src/components/base/tooltip/tooltip.vue
packages/wiz-ui-next/src/components/custom/chat/card/chat-card.stories.ts
packages/wiz-ui-next/src/components/custom/chat/item/chat-item.stories.ts
packages/wiz-ui-next/src/components/custom/chat/item/chat-item.vue
packages/wiz-ui-next/src/components/custom/chat/types.ts
packages/wiz-ui/src/components/base/tooltip/tooltip.vue
packages/wiz-ui/src/components/custom/chat/card/chat-card.stories.ts
packages/wiz-ui/src/components/custom/chat/item/chat-item.stories.ts
packages/wiz-ui/src/components/custom/chat/item/chat-item.vue
packages/wiz-ui/src/components/custom/chat/types.ts

Feat(ChatCard): 既読件数表示、既読Tooltip表示

---

packages/styles/bases/anchor.css.ts
packages/utils/index.ts
packages/utils/linkify.ts
packages/wiz-ui-next/src/components/base/text/text.vue
packages/wiz-ui-next/src/components/custom/chat/card/chat-card.stories.ts
packages/wiz-ui-next/src/components/custom/chat/item/chat-item.stories.ts
packages/wiz-ui-next/src/components/custom/chat/item/chat-item.vue
packages/wiz-ui/src/components/base/text/text.vue
packages/wiz-ui/src/components/custom/chat/card/chat-card.stories.ts
packages/wiz-ui/src/components/custom/chat/item/chat-item.stories.ts
packages/wiz-ui/src/components/custom/chat/item/chat-item.vue

Feat(ChatCard): URLをリンク化する処理の追加、長い英文字の折り返し処理

---

.github/composite/prepare_node/action.yml
packages/wiz-ui-next/src/components/base/textarea/text-area.vue
packages/wiz-ui/src/components/base/textarea/text-area.stories.ts
packages/wiz-ui/src/components/base/textarea/text-area.vue

ci: node_modulesのキャッシュ管理方法をaction/cacheに変更

---

packages/wiz-ui-next/src/components/base/inputs/radio/radio.stories.ts
packages/wiz-ui-next/src/components/base/inputs/radio/radio.vue
packages/wiz-ui-next/src/components/base/inputs/radio/types.ts
packages/wiz-ui-next/src/components/custom/form/group.stories.ts
packages/wiz-ui/src/components/base/inputs/radio/radio.stories.ts
packages/wiz-ui/src/components/base/inputs/radio/radio.vue
packages/wiz-ui/src/components/base/inputs/radio/types.ts
packages/wiz-ui/src/components/custom/form/group.stories.ts

radioのoptionのkeyを指定できるように

---

packages/wiz-ui-next/src/components/base/buttons/toggle/toggle.stories.ts
packages/wiz-ui-next/src/components/base/buttons/toggle/toggle.vue
packages/wiz-ui/src/components/base/buttons/toggle/toggle.stories.ts
packages/wiz-ui/src/components/base/buttons/toggle/toggle.vue

feat(toggle-button): アクティブかどうかをv-modelで制御する

---

packages/wiz-ui-next/src/components/base/inputs/toggle-switch/toggle-switch.vue
packages/wiz-ui/src/components/base/inputs/toggle-switch/toggle-switch.vue

fix(toggle-switch): Labelをつける

---

packages/styles/bases/text.css.ts
packages/wiz-ui-next/src/components/base/text/text.stories.ts
packages/wiz-ui-next/src/components/base/text/text.vue
packages/wiz-ui/src/components/base/text/text.stories.ts
packages/wiz-ui/src/components/base/text/text.vue

feat(wiztext): text-alignプロパティを追加

---

packages/styles/bases/calendar.css.ts
packages/wiz-ui-next/src/components/base/calendar/calendar.vue
packages/wiz-ui/src/components/base/calendar/calendar.vue

fix(calender): 当月以外の日付のコントラストを落とす

---

packages/wiz-ui-next/src/components/base/menu/menu-item.vue
packages/wiz-ui/src/components/base/menu/menu-item.vue

fix(menu-item): アイテム外でクリックを離したとき非アクティブにする

---

packages/wiz-ui-next/src/components/base/progress-bar/progress-bar.vue
packages/wiz-ui/src/components/base/progress-bar/progress-bar.vue

fix/Bug: WizProgressBarのtooltipが機能していない

---

packages/styles/bases/checkbox-input.css.ts

fix(check-box): lineHeightを100%に設定

---

packages/wiz-ui-next/src/components/base/buttons/index.ts
packages/wiz-ui/src/components/base/buttons/index.ts

fix: tiny-buttonのexportを追加

---

packages/wiz-ui-next/src/components/custom/notification/list/list.vue
packages/wiz-ui-next/src/components/custom/notification/notification.stories.ts
packages/wiz-ui-next/src/components/custom/notification/notification.vue
packages/wiz-ui/src/components/custom/notification/list/list.vue
packages/wiz-ui/src/components/custom/notification/notification.stories.ts
packages/wiz-ui/src/components/custom/notification/notification.vue

Feat(Notification): notificationsが空の時にメッセージを出せるようにする

---

packages/wiz-ui-next/src/components/base/box/box.vue
packages/wiz-ui/src/components/base/box/box.vue

feat(box): backdrop blur要素を追加

---

packages/wiz-ui-next/src/components/base/buttons/tiny/tiny.stories.ts
packages/wiz-ui-next/src/components/base/buttons/tiny/tiny.vue
packages/wiz-ui/src/components/base/buttons/tiny/tiny.vue

tinyButtonのクリックが反応するように

---

packages/wiz-ui-next/src/components/base/buttons/tiny/tiny.stories.ts
packages/wiz-ui-next/src/components/base/buttons/tiny/tiny.vue
packages/wiz-ui/src/components/base/buttons/tiny/tiny.stories.ts
packages/wiz-ui/src/components/base/buttons/tiny/tiny.vue

Feat(WizTinyButton):  p/px/pyでspacingを指定する

---

packages/styles/bases/tiny-button.css.ts
packages/wiz-ui-next/src/components/base/buttons/tiny/tiny.stories.ts
packages/wiz-ui-next/src/components/base/buttons/tiny/tiny.vue
packages/wiz-ui/src/components/base/buttons/tiny/tiny.stories.ts
packages/wiz-ui/src/components/base/buttons/tiny/tiny.vue

fix(tiny-button): disabledを修正

---

packages/wiz-ui-next/src/components/base/dropdown/dropdown.vue
packages/wiz-ui-next/src/components/base/inputs/datepicker/date-picker.vue
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui-next/src/components/base/inputs/timepicker/time-picker.vue
packages/wiz-ui-next/src/components/base/popup/popup-container.vue
packages/wiz-ui-next/src/components/base/popup/popup.stories.ts
packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui-next/src/components/base/popup/provider.ts
packages/wiz-ui-next/src/hooks/use-click-outside.ts
packages/wiz-ui/src/components/base/dropdown/dropdown.vue
packages/wiz-ui/src/components/base/inputs/datepicker/date-picker.vue
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui/src/components/base/inputs/timepicker/time-picker.vue
packages/wiz-ui/src/components/base/popup/popup-container.vue
packages/wiz-ui/src/components/base/popup/popup.stories.ts
packages/wiz-ui/src/components/base/popup/popup.vue
packages/wiz-ui/src/components/base/popup/provider.ts
packages/wiz-ui/src/hooks/use-click-outside.ts

resolve: #404
- useClickOutside周りの改修
- 変数elを削除し、直接refを見る形に変更
- クリックした対象がpopup以外で、かつcloseOnBlurがtrueのときはpopupを閉じる処理を追加

bug: useClickOutside問題の解消

---

examples/vue2/src/components/layout/header/notification-dropdown.vue
examples/vue3/src/components/layout/header/notification-dropdown.vue
packages/wiz-ui-next/src/components/base/inputs/search/search.stories.ts
packages/wiz-ui-next/src/components/base/inputs/search/search.vue
packages/wiz-ui/src/components/base/inputs/search/search.stories.ts
packages/wiz-ui/src/components/base/inputs/search/search.vue

resolve: #407
**以下のPRに依存しています**
- #331 
- #389 
- #406

feat: search-inputの新しいpopup対応

---

packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui/src/components/base/popup/popup.vue

update(popup): layerのdefaultをpopoverに変更

---

packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui/src/components/base/popup/popup.vue

Bug(popup): 画面幅が変わったときにpopupが追従しない

---

packages/styles/bases/popup.css.ts
packages/wiz-ui-next/src/components/base/popup/popup-container.vue
packages/wiz-ui-next/src/components/base/popup/popup.stories.ts
packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui-next/src/hooks/use-scroll.ts
packages/wiz-ui/src/components/base/popup/popup-container.vue
packages/wiz-ui/src/components/base/popup/popup.stories.ts
packages/wiz-ui/src/components/base/popup/popup.vue
packages/wiz-ui/src/hooks/use-scroll.ts

Bug(popup): ダイアログに縦に長いpopupを乗せたときに突き抜ける & Controllerに追従しない

---

packages/styles/bases/snackbar.css.ts

Bug(snackbar): close buttonにpaddingが残っている

---

packages/styles/bases/navigation.css.ts
packages/wiz-ui-next/package.json
packages/wiz-ui-next/src/index.ts
packages/wiz-ui/package.json
packages/wiz-ui/src/index.ts

Release: v0.7.4

---

packages/wiz-ui-next/src/hooks/use-snackbar.ts
packages/wiz-ui/src/hooks/use-snackbar.ts

Bug(snackbar): 同一ページで複数個所からuseSnackbarを使うと出ない

---

packages/styles/bases/card-table.css.ts
packages/styles/bases/flat-table.css.ts
packages/styles/bases/unstyled-table.css.ts
packages/wiz-ui-next/src/components/base/tables/card/table.stories.ts
packages/wiz-ui-next/src/components/base/tables/card/table.vue
packages/wiz-ui-next/src/components/base/tables/flat/table.stories.ts
packages/wiz-ui-next/src/components/base/tables/flat/table.vue
packages/wiz-ui-next/src/components/base/tables/unstyled/table.stories.ts
packages/wiz-ui-next/src/components/base/tables/unstyled/table.vue
packages/wiz-ui/src/components/base/tables/card/table.stories.ts
packages/wiz-ui/src/components/base/tables/card/table.vue
packages/wiz-ui/src/components/base/tables/flat/table.stories.ts
packages/wiz-ui/src/components/base/tables/flat/table.vue
packages/wiz-ui/src/components/base/tables/unstyled/table.stories.ts
packages/wiz-ui/src/components/base/tables/unstyled/table.vue

Feat: table-layout 機能を追加

---

packages/styles/bases/navigation.css.ts
packages/wiz-ui-next/src/components/base/navigation/item.stories.ts
packages/wiz-ui-next/src/components/base/navigation/item.vue
packages/wiz-ui/src/components/base/navigation/item.stories.ts
packages/wiz-ui/src/components/base/navigation/item.vue

[Feat]: WizNavItem に disabled 属性と tooltip 機能を追加

---

packages/wiz-ui/regconfig.json

https://speakerdeck.com/andpad/vrtyatutemasuka-reg-suitdesuka?slide=65

fix: reg suitの差分検出が厳格すぎるので緩和

---

packages/styles/bases/search-selector.css.ts
packages/wiz-ui-next/src/components/base/inputs/search-selector/search-selector.stories.ts
packages/wiz-ui/src/components/base/inputs/search-selector/search-selector.stories.ts

fix: Search Select のラベルに ellipsis を適用する

---

packages/wiz-ui/src/components/base/inputs/date-picker/date-picker.stories.ts

fix(date-picker): placeholderが表示されるようにする

---

packages/styles/bases/checkbox-input.css.ts
packages/styles/bases/radio-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/checkbox/checkbox.stories.ts
packages/wiz-ui-next/src/components/base/inputs/checkbox/checkbox.vue
packages/wiz-ui-next/src/components/base/inputs/radio/radio.stories.ts
packages/wiz-ui-next/src/components/base/inputs/radio/radio.vue
packages/wiz-ui/src/components/base/inputs/checkbox/checkbox.stories.ts
packages/wiz-ui/src/components/base/inputs/checkbox/checkbox.vue
packages/wiz-ui/src/components/base/inputs/radio/radio.stories.ts
packages/wiz-ui/src/components/base/inputs/radio/radio.vue

Radio, Checkbox のコンポーネントに打ち消し線を追加

---

packages/wiz-ui-next/src/components/base/popup/popup-container.vue
packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui-next/src/hooks/use-scroll.ts
packages/wiz-ui/src/components/base/popup/popup-container.vue
packages/wiz-ui/src/components/base/popup/popup.vue
packages/wiz-ui/src/hooks/use-scroll.ts

Feat(popup): body要素以外もscrollイベントが発火できるようにした

---

packages/wiz-ui/src/components/base/inputs/search/search-popup.vue
packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue

fix: build error

---

packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.stories.ts
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.stories.ts
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.vue

Feat(selectbox): 開いた状態のselectboxのStoryを追加する 

---

packages/wiz-ui-next/src/components/custom/chat/card/chat-card.vue
packages/wiz-ui/src/components/custom/chat/card/chat-card.vue

Bug(WizChatCard): セレクタを入れると引っ込めた時にその分はみ出す

---

packages/styles/bases/unstyled-table.css.ts
packages/wiz-ui-next/src/components/base/tables/unstyled/table.stories.ts
packages/wiz-ui-next/src/components/base/tables/unstyled/table.vue
packages/wiz-ui-next/src/components/base/tables/unstyled/thead.vue
packages/wiz-ui-next/src/components/base/tables/unstyled/tr.vue
packages/wiz-ui/src/components/base/tables/unstyled/table.stories.ts
packages/wiz-ui/src/components/base/tables/unstyled/table.vue
packages/wiz-ui/src/components/base/tables/unstyled/thead.vue
packages/wiz-ui/src/components/base/tables/unstyled/tr.vue

Feat(Unstyled Table): dividerを持つことのできるパラメータの追加

---

packages/styles/bases/unstyled-table.css.ts
packages/wiz-ui-next/package.json
packages/wiz-ui-next/src/components/base/tables/unstyled/table.stories.ts
packages/wiz-ui-next/src/components/base/tables/unstyled/table.vue
packages/wiz-ui-next/src/components/base/tables/unstyled/thead.vue
packages/wiz-ui-next/src/components/base/tables/unstyled/tr.vue
packages/wiz-ui-next/src/index.ts
packages/wiz-ui/package.json
packages/wiz-ui/src/components/base/tables/unstyled/table.stories.ts
packages/wiz-ui/src/components/base/tables/unstyled/table.vue
packages/wiz-ui/src/components/base/tables/unstyled/thead.vue
packages/wiz-ui/src/components/base/tables/unstyled/tr.vue
packages/wiz-ui/src/index.ts

Release: v0.7.9

---

packages/styles/bases/date-picker-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/date-picker/date-picker.vue
packages/wiz-ui-next/src/components/base/inputs/date-range-picker/date-range-picker.vue
packages/wiz-ui/src/components/base/inputs/date-picker/date-picker.vue
packages/wiz-ui/src/components/base/inputs/date-range-picker/date-range-picker.vue

Bug(datepicker): popupの回り込みがきかない

---

packages/styles/bases/popup.css.ts
packages/styles/bases/progress-bar.css.ts
packages/styles/bases/tooltip.css.ts
packages/wiz-ui-next/src/components/base/popup/popup.stories.ts
packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui-next/src/components/base/progress-bar/progress-bar.vue
packages/wiz-ui-next/src/components/base/tooltip/tooltip.stories.ts
packages/wiz-ui-next/src/components/base/tooltip/tooltip.vue
packages/wiz-ui/src/components/base/popup/popup.stories.ts
packages/wiz-ui/src/components/base/popup/popup.vue
packages/wiz-ui/src/components/base/progress-bar/progress-bar.vue
packages/wiz-ui/src/components/base/tooltip/tooltip.stories.ts
packages/wiz-ui/src/components/base/tooltip/tooltip.vue

Feat(tooltip): TooltipをPopupManager実装に変える

---

LICENSE
README.md
packages/wiz-ui-next/package.json
packages/wiz-ui-next/vite.config.ts
packages/wiz-ui/package.json
packages/wiz-ui/vite.config.ts

Chore: wiz-uiのライセンス設定

---

packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui-next/src/components/base/popup/provider.ts
packages/wiz-ui/src/components/base/popup/popup.vue
packages/wiz-ui/src/components/base/popup/provider.ts

Bug(tooltip): 最初から画面外にあるtooltipの表示位置が回り込み済みのものとなってしまう

---

README.md
packages/wiz-ui-next/package.json
packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui-next/src/components/base/popup/provider.ts
packages/wiz-ui-next/src/index.ts
packages/wiz-ui/package.json
packages/wiz-ui/src/components/base/popup/popup.vue
packages/wiz-ui/src/components/base/popup/provider.ts
packages/wiz-ui/src/index.ts

Release: 1.0.2

---

packages/styles/bases/dialog.css.ts
packages/wiz-ui-next/src/components/base/dialog/dialog.vue
packages/wiz-ui/src/components/base/dialog/dialog.vue

feat(dialog): ダイアログ表示時にスクロールをできないようにする

---

.changeset/bright-moons-allow.md
packages/wiz-ui-next/CHANGELOG.md
packages/wiz-ui-next/package.json
packages/wiz-ui/CHANGELOG.md
packages/wiz-ui/package.json

Reverts Wizleap-Inc/wiz-ui#521

Revert "Version Packages"

---

.changeset/lucky-laws-exercise.md
packages/wiz-ui-react/package.json
pnpm-lock.yaml

chore: add clsx

---

.changeset/brave-baboons-impress.md
packages/constants/styles/color.ts

feat(constants): gray.200の追加

---

.changeset/breezy-moose-vanish.md

chore(changeset): warning icon

---

.changeset/rude-cycles-knock.md
packages/styles/bases/tiny-button.css.ts
packages/wiz-ui-next/src/components/base/buttons/tiny/tiny.vue
packages/wiz-ui/src/components/base/buttons/tiny/tiny.vue

fix(tiny-button): paddingの上書きを回避

---

packages/wiz-ui-react/vite.config.ts

Reactが一緒にbundleされていてminifyできていなかったので外部呼び出し方式に修正

fix(react): import react from external

---

.changeset/rotten-ligers-sip.md
packages/styles/bases/tag.css.ts
packages/wiz-ui-next/src/components/base/tag/tag.stories.ts
packages/wiz-ui-next/src/components/base/tag/tag.vue
packages/wiz-ui/src/components/base/tag/tag.stories.ts
packages/wiz-ui/src/components/base/tag/tag.vue

Feat(tag): variant変更・新規タグ追加

---

.changeset/cyan-drinks-drive.md
packages/wiz-ui-next/src/components/base/snackbar/snackbar.stories.ts
packages/wiz-ui-next/src/components/manager/provider.vue
packages/wiz-ui-next/src/hooks/index.ts
packages/wiz-ui-next/src/hooks/use-global-provider.ts
packages/wiz-ui-next/src/hooks/use-snackbar.ts
packages/wiz-ui-next/src/index.ts
packages/wiz-ui/src/components/base/snackbar/snackbar.stories.ts
packages/wiz-ui/src/components/manager/provider.vue
packages/wiz-ui/src/hooks/index.ts
packages/wiz-ui/src/hooks/use-global-provider.ts
packages/wiz-ui/src/hooks/use-snackbar.ts
packages/wiz-ui/src/index.ts

Bug(snackbar): snackbarが使えない

---

.changeset/loud-ties-type.md
packages/wiz-ui-next/src/components/base/dialog/dialog.stories.ts
packages/wiz-ui-next/src/components/base/dialog/dialog.vue
packages/wiz-ui/src/components/base/dialog/dialog.stories.ts
packages/wiz-ui/src/components/base/dialog/dialog.vue

Add a hideClose prop in dialog

---

.changeset/old-lions-serve.md
packages/wiz-ui-next/src/components/base/inputs/date-picker/date-picker.stories.ts
packages/wiz-ui-next/src/components/base/inputs/date-picker/date-picker.vue
packages/wiz-ui-next/src/components/base/inputs/date-range-picker/date-range-picker.stories.ts
packages/wiz-ui-next/src/components/base/inputs/date-range-picker/date-range-picker.vue
packages/wiz-ui-next/src/components/base/inputs/date-range-picker/types.ts
packages/wiz-ui/src/components/base/inputs/date-picker/date-picker.stories.ts
packages/wiz-ui/src/components/base/inputs/date-picker/date-picker.vue
packages/wiz-ui/src/components/base/inputs/date-range-picker/date-range-picker.stories.ts
packages/wiz-ui/src/components/base/inputs/date-range-picker/date-range-picker.vue
packages/wiz-ui/src/components/base/inputs/date-range-picker/types.ts

Feat(date-picker/date-range-picker): カレンダーに初期値を反映する

---

.changeset/fresh-poets-study.md
packages/constants/component/name.ts
packages/styles/bases/information-panel.css.ts
packages/wiz-ui-next/src/components/base/information-panel/index.ts
packages/wiz-ui-next/src/components/base/information-panel/information-panel.stories.ts
packages/wiz-ui-next/src/components/base/information-panel/information-panel.vue
packages/wiz-ui/src/components/base/information-panel/index.ts
packages/wiz-ui/src/components/base/information-panel/information-panel.stories.ts
packages/wiz-ui/src/components/base/information-panel/information-panel.vue

Information Panel の追加

---

.changeset/fresh-poets-study.md
packages/constants/component/name.ts
packages/styles/bases/information-panel.css.ts
packages/wiz-ui-next/src/components/base/information-panel/index.ts
packages/wiz-ui-next/src/components/base/information-panel/information-panel.stories.ts
packages/wiz-ui-next/src/components/base/information-panel/information-panel.vue
packages/wiz-ui/src/components/base/information-panel/index.ts
packages/wiz-ui/src/components/base/information-panel/information-panel.stories.ts
packages/wiz-ui/src/components/base/information-panel/information-panel.vue

Reverts Wizleap-Inc/wiz-ui#808

Revert "Revert "Information Panel の追加""

---

.changeset/fifty-bulldogs-cover.md
packages/styles/bases/dropdown.css.ts
packages/wiz-ui-next/src/components/base/dropdown/dropdown-item.stories.ts
packages/wiz-ui-next/src/components/base/dropdown/dropdown-item.vue
packages/wiz-ui-next/src/components/base/dropdown/dropdown.stories.ts
packages/wiz-ui/src/components/base/dropdown/dropdown-item.stories.ts
packages/wiz-ui/src/components/base/dropdown/dropdown-item.vue
packages/wiz-ui/src/components/base/dropdown/dropdown.stories.ts

Feat(dropdown-item): disabledプロパティを追加

---

.changeset/tall-peas-sit.md
packages/wiz-ui-next/src/components/base/menu/menu-item.stories.ts
packages/wiz-ui-next/src/components/base/menu/menu-item.vue
packages/wiz-ui/src/components/base/menu/menu-item.stories.ts
packages/wiz-ui/src/components/base/menu/menu-item.vue

Feat(menu-item): fontSizeプロパティを追加

---

.changeset/chilly-brooms-think.md
packages/styles/bases/toggle-switch-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/toggle-switch/toggle-switch.stories.ts
packages/wiz-ui-next/src/components/base/inputs/toggle-switch/toggle-switch.vue
packages/wiz-ui/src/components/base/inputs/toggle-switch/toggle-switch.stories.ts
packages/wiz-ui/src/components/base/inputs/toggle-switch/toggle-switch.vue

ToggleSwitch に default color を設定

---

.changeset/popular-teachers-do.md
packages/wiz-ui-react/src/components/base/graphs/circle/components/bar.tsx
packages/wiz-ui-react/src/components/base/graphs/circle/components/circle-graph.tsx
packages/wiz-ui-react/src/components/base/graphs/circle/components/index.ts
packages/wiz-ui-react/src/components/base/graphs/circle/components/types.ts
packages/wiz-ui-react/src/components/base/graphs/circle/index.ts
packages/wiz-ui-react/src/components/base/graphs/circle/stories/circle-graph.stories.tsx
packages/wiz-ui-react/src/components/base/graphs/index.ts
packages/wiz-ui-react/src/components/base/index.ts

WizCircleGraphのReact対応

---

.changeset/silent-ties-cheer.md
packages/styles/bases/date-picker-input.css.ts
packages/styles/bases/time-picker-input.css.ts
packages/wiz-ui-next/src/components/base/dropdown/dropdown.stories.ts
packages/wiz-ui-next/src/components/base/inputs/date-picker/date-picker.stories.ts
packages/wiz-ui-next/src/components/base/inputs/date-range-picker/date-range-picker.stories.ts
packages/wiz-ui-next/src/components/base/inputs/search-input/search.stories.ts
packages/wiz-ui-next/src/components/base/inputs/search-selector/search-selector.stories.ts
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.stories.ts
packages/wiz-ui-next/src/components/base/inputs/timepicker/time-picker.stories.ts
packages/wiz-ui-next/src/components/base/inputs/timepicker/time-picker.vue
packages/wiz-ui-next/src/components/base/tooltip/tooltip.stories.ts
packages/wiz-ui/src/components/base/dropdown/dropdown.stories.ts
packages/wiz-ui/src/components/base/inputs/date-picker/date-picker.stories.ts
packages/wiz-ui/src/components/base/inputs/timepicker/time-picker.stories.ts
packages/wiz-ui/src/components/base/inputs/timepicker/time-picker.vue

disabled color in datetimepicker

---

.changeset/twelve-students-reflect.md
packages/styles/bases/message-box.css.ts
packages/wiz-ui-next/src/components/base/message-box/message-box.stories.ts
packages/wiz-ui/src/components/base/message-box/message-box.stories.ts

Message box で icon の幅が変化するバグの修正

---

.changeset/brown-terms-search.md
packages/wiz-ui-react/src/components/base/dialog/components/dialog.tsx

[React] Dialogのクリンナップ処理を修正

---

.changeset/unlucky-peaches-count.md
packages/wiz-ui-react/src/components/base/heading/components/heading.tsx
packages/wiz-ui-react/src/components/base/heading/components/index.ts
packages/wiz-ui-react/src/components/base/heading/index.ts
packages/wiz-ui-react/src/components/base/heading/stories/heading.stories.tsx
packages/wiz-ui-react/src/components/base/index.ts

Feat: WizHeadingのReact対応

---

.changeset/mighty-drinks-reply.md
packages/wiz-ui-next/src/components/base/popup/popup.stories.ts
packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui/src/components/base/popup/popup.stories.ts
packages/wiz-ui/src/components/base/popup/popup.vue

Fix(popup): fixedされたpopupの位置計算にスクロール量が算入される

---

packages/wiz-ui-next/src/components/base/tooltip/tooltip.stories.ts
packages/wiz-ui-react/src/components/base/tooltip/stories/tooltip.stories.tsx
regconfig.json

test: VRTでのフレーキーな差分検出を回避

---

.changeset/wet-dolls-grin.md
packages/wiz-ui-react/src/components/base/dropdown/components/dropdown-item.tsx
packages/wiz-ui-react/src/components/base/dropdown/components/dropdown.tsx
packages/wiz-ui-react/src/components/base/dropdown/components/index.ts
packages/wiz-ui-react/src/components/base/dropdown/index.ts
packages/wiz-ui-react/src/components/base/dropdown/stories/dropdown-item.stories.tsx
packages/wiz-ui-react/src/components/base/dropdown/stories/dropdown.stories.tsx
packages/wiz-ui-react/src/components/base/index.ts

feat: WizDropdownのReact対応

---

.changeset/large-teachers-rest.md
packages/wiz-ui-next/src/components/base/popup-button-group/popup-button-group.vue
packages/wiz-ui-react/src/components/base/index.ts
packages/wiz-ui-react/src/components/base/popup-button-group/components/button-item.tsx
packages/wiz-ui-react/src/components/base/popup-button-group/components/divider-item.tsx
packages/wiz-ui-react/src/components/base/popup-button-group/components/group-item.tsx
packages/wiz-ui-react/src/components/base/popup-button-group/components/index.ts
packages/wiz-ui-react/src/components/base/popup-button-group/components/popup-button-group.tsx
packages/wiz-ui-react/src/components/base/popup-button-group/index.ts
packages/wiz-ui-react/src/components/base/popup-button-group/stories/popup-button-group.stories.tsx
packages/wiz-ui-react/src/components/base/popup-button-group/types.ts

Feat: WizPopupButtonGroupのReact対応

---

.changeset/gold-tables-beg.md
packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui/src/components/base/inputs/search-input/search-input.vue

[#736] WizSearch の expand 機能修正

---

.changeset/calm-ants-push.md
packages/wiz-ui-react/src/components/base/index.ts
packages/wiz-ui-react/src/components/base/snackbar/components/index.ts
packages/wiz-ui-react/src/components/base/snackbar/components/snackbar-context.tsx
packages/wiz-ui-react/src/components/base/snackbar/components/snackbar-provider.tsx
packages/wiz-ui-react/src/components/base/snackbar/components/snackbar.tsx
packages/wiz-ui-react/src/components/base/snackbar/index.ts
packages/wiz-ui-react/src/components/base/snackbar/stories/snackbar.stories.tsx

feat: WizSnackbarのReact対応

---

.changeset/orange-pianos-cover.md
packages/wiz-ui-react/src/components/base/inputs/index.ts
packages/wiz-ui-react/src/components/base/inputs/upload/components/index.ts
packages/wiz-ui-react/src/components/base/inputs/upload/components/upload-display.tsx
packages/wiz-ui-react/src/components/base/inputs/upload/components/upload-input.tsx
packages/wiz-ui-react/src/components/base/inputs/upload/index.ts
packages/wiz-ui-react/src/components/base/inputs/upload/stories/uplaod-input.stories.tsx

Feat: WizUploadInputのReact対応

---

.changeset/shiny-houses-impress.md
packages/wiz-ui-react/src/components/base/inputs/index.ts
packages/wiz-ui-react/src/components/base/inputs/selectbox/components/index.ts
packages/wiz-ui-react/src/components/base/inputs/selectbox/components/selectbox.tsx
packages/wiz-ui-react/src/components/base/inputs/selectbox/index.ts
packages/wiz-ui-react/src/components/base/inputs/selectbox/stories/selectbox.stories.tsx

feat: WizSelectBoxのReact対応

---

.changeset/silver-seahorses-cross.md
packages/wiz-ui-react/src/components/base/tab/components/tab-pane.tsx
packages/wiz-ui-react/src/components/custom/index.ts
packages/wiz-ui-react/src/components/custom/notification/components/index.ts
packages/wiz-ui-react/src/components/custom/notification/components/notification-list.tsx
packages/wiz-ui-react/src/components/custom/notification/components/notification-panel.tsx
packages/wiz-ui-react/src/components/custom/notification/components/notification.tsx
packages/wiz-ui-react/src/components/custom/notification/components/types.ts
packages/wiz-ui-react/src/components/custom/notification/index.ts
packages/wiz-ui-react/src/components/custom/notification/stories/notification-list.stories.tsx
packages/wiz-ui-react/src/components/custom/notification/stories/notification-panel.stories.tsx
packages/wiz-ui-react/src/components/custom/notification/stories/notification.stories.tsx

resolve: #868 
* 追加対応
* WizTab の通知表示の判定を修正

feat: WizNotificationのReact対応

---

.changeset/ten-apples-reply.md
packages/styles/bases/time-picker-input.css.ts

time-pickerのfontSizeをxsに

---

.changeset/serious-pigs-rule.md
packages/wiz-ui-next/src/components/base/inputs/date-range-picker/date-range-picker.stories.ts
packages/wiz-ui-next/src/components/base/inputs/date-range-picker/date-range-picker.vue
packages/wiz-ui/src/components/base/inputs/date-range-picker/date-range-picker.stories.ts
packages/wiz-ui/src/components/base/inputs/date-range-picker/date-range-picker.vue

Fix(date-range-picker): disabed font color

---

.changeset/pink-swans-march.md
packages/styles/bases/message-box.css.ts

fix(message-box): 外側のtext-alignの影響を受けないようにする

---

.changeset/nasty-apples-allow.md
packages/wiz-ui-next/src/components/base/information-panel/information-panel.vue
packages/wiz-ui/src/components/base/information-panel/information-panel.vue

fix(information-panel): 不要なalignの削除

---

.changeset/quick-dryers-suffer.md
packages/wiz-ui-react/src/components/base/index.ts
packages/wiz-ui-react/src/components/base/text-area/components/index.ts
packages/wiz-ui-react/src/components/base/text-area/components/text-area.tsx
packages/wiz-ui-react/src/components/base/text-area/index.ts
packages/wiz-ui-react/src/components/base/text-area/stories/text-area.stories.tsx

feat: WizTextAreaのReact対応

---

packages/wiz-ui-react/src/components/base/text-area/stories/text-area.stories.tsx

test: storybook テストが落ちるのを一旦回避

---

.changeset/odd-meals-grow.md
packages/wiz-ui-react/src/components/base/index.ts

feat:(WizSkeleton) コンポーネントのexportを追加

---

.changeset/small-seas-draw.md
packages/wiz-ui-react/src/components/base/popup/components/popup.tsx
packages/wiz-ui-react/src/components/base/popup/utils/index.ts
packages/wiz-ui-react/src/components/base/popup/utils/wrap.ts

feat(popup): 回り込みの挙動改善

---

.changeset/afraid-singers-refuse.md
packages/wiz-ui-react/src/components/base/popup/components/popup.tsx
packages/wiz-ui-react/src/components/base/tooltip/components/tooltip.tsx
packages/wiz-ui-react/src/components/custom/chat/components/chat-card.tsx
packages/wiz-ui-react/src/components/custom/chat/components/chat-form.tsx
packages/wiz-ui-react/src/components/custom/chat/components/chat-item.tsx
packages/wiz-ui-react/src/components/custom/chat/components/index.ts
packages/wiz-ui-react/src/components/custom/chat/components/types.ts
packages/wiz-ui-react/src/components/custom/chat/index.ts
packages/wiz-ui-react/src/components/custom/chat/stories/chat-card.stories.tsx
packages/wiz-ui-react/src/components/custom/chat/stories/chat-form.stories.tsx
packages/wiz-ui-react/src/components/custom/chat/stories/chat-item.stories.tsx
packages/wiz-ui-react/src/components/custom/index.ts

feat: chat の React 対応

---

.changeset/late-cherries-travel.md
packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui/src/components/base/inputs/search-input/search-input.vue

fix(search-input): 検索結果が空のときの表示

---

.changeset/fuzzy-boxes-divide.md
packages/wiz-ui-react/src/components/base/index.ts
packages/wiz-ui-react/src/components/base/information-panel/components/index.ts
packages/wiz-ui-react/src/components/base/information-panel/components/information-panel.tsx
packages/wiz-ui-react/src/components/base/information-panel/index.ts
packages/wiz-ui-react/src/components/base/information-panel/stories/information-panel.stories.tsx

feat: WizInformationPanelのReact対応

---

.changeset/young-timers-divide.md
packages/styles/bases/radio-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/radio/radio.vue
packages/wiz-ui/src/components/base/inputs/radio/radio.vue

ラジオボタンの a11y 対応 

---

.changeset/metal-elephants-cheer.md
packages/constants/component/name.ts
packages/styles/bases/calendar.css.ts
packages/wiz-ui-react/src/components/base/calendar/components/calendar.tsx
packages/wiz-ui-react/src/components/base/inputs/date-range-picker/components/date-range-picker.tsx
packages/wiz-ui-react/src/components/base/inputs/date-range-picker/components/index.ts
packages/wiz-ui-react/src/components/base/inputs/date-range-picker/index.ts
packages/wiz-ui-react/src/components/base/inputs/date-range-picker/stories/date-range-picker.stories.tsx
packages/wiz-ui-react/src/components/base/inputs/date-range-picker/types/date-range.ts
packages/wiz-ui-react/src/components/base/inputs/date-range-picker/types/index.ts
packages/wiz-ui-react/src/components/base/inputs/index.ts

feat(date-range-picker): react対応

---

.changeset/olive-pants-tease.md
packages/wiz-ui-next/src/components/base/navigation/container.stories.ts
packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui/src/components/base/navigation/container.stories.ts
packages/wiz-ui/src/components/base/popup/popup.vue

Feat(popup): sticky対応

---

.changeset/late-kids-fix.md
packages/styles/bases/radio-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/radio/radio.stories.ts
packages/wiz-ui/src/components/base/inputs/radio/radio.stories.ts

Fix(radio): lineHeightを修正

---

.changeset/twenty-mangos-shake.md
packages/styles/bases/text-button.css.ts

Fix(text-button): whitespace nowrap

---

.changeset/purple-scissors-sing.md
packages/wiz-ui-react/src/components/base/index.ts

feat: tablesディレクトリをexport

---

.changeset/perfect-ads-chew.md
packages/wiz-ui-next/src/components/base/tab/tab.stories.ts
packages/wiz-ui-next/src/components/base/tab/tab.vue
packages/wiz-ui-react/src/components/base/tab/components/tab.tsx
packages/wiz-ui-react/src/components/base/tab/stories/tab.stories.tsx
packages/wiz-ui/src/components/base/tab/tab.stories.ts
packages/wiz-ui/src/components/base/tab/tab.vue

Feat(tab): タブを中央寄せにするオプションを追加

---

examples/vue3/package.json
examples/vue3/src/components/layout/navigation/nav-list.vue
examples/vue3/src/pages/chat.vue
examples/vue3/src/pages/chat/_components/chat-form.vue
examples/vue3/src/pages/chat/_components/chat-log.vue
examples/vue3/src/pages/chat/_components/index.ts
examples/vue3/src/pages/chat/_components/template.ts
examples/vue3/src/pages/chat/index.vue
examples/vue3/src/router/index.ts
pnpm-lock.yaml

chore(example): chat画面をwiz-uiで組み立てる

---

.changeset/sweet-impalas-shop.md
packages/wiz-ui-react/src/components/base/anchor/components/anchor.tsx
packages/wiz-ui-react/src/components/base/anchor/stories/anchor.stories.tsx
packages/wiz-ui-react/src/components/custom/chat/components/chat-item.tsx

Fix: WizAnchor(React)のreact-router対応

---

.changeset/yellow-moons-remember.md
packages/wiz-ui-next/src/components/base/header/header.stories.ts
packages/wiz-ui-next/src/components/base/header/header.vue
packages/wiz-ui/src/components/base/header/header.stories.ts
packages/wiz-ui/src/components/base/header/header.vue

fix: headerの仕様をreactと合わせる

---

.changeset/five-mirrors-shave.md
packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui-next/src/components/base/inputs/search-input/stories/search-input.stories.ts
packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-input.tsx
packages/wiz-ui-react/src/components/base/inputs/search-input/stories/search-input.stories.tsx
packages/wiz-ui/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui/src/components/base/inputs/search-input/stories/search-input.stories.ts

Feat(search-input): アイコンを外側から受け付けられるようにする

---

.changeset/tame-chicken-punch.md
packages/styles/bases/calendar.css.ts
packages/wiz-ui-next/src/components/base/calendar/calendar.vue
packages/wiz-ui-next/src/components/base/inputs/date-picker/date-picker.stories.ts
packages/wiz-ui-next/src/components/base/inputs/date-picker/date-picker.vue
packages/wiz-ui/src/components/base/calendar/calendar.vue
packages/wiz-ui/src/components/base/inputs/date-picker/date-picker.stories.ts
packages/wiz-ui/src/components/base/inputs/date-picker/date-picker.vue

Feat(calendar, date-picker): 無効な日付をクリック不可にする

---

.changeset/three-masks-battle.md
packages/wiz-ui-react/src/components/base/inputs/checkbox/components/checkbox.tsx
packages/wiz-ui-react/src/components/base/inputs/radio/components/radio.tsx
packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-input.tsx
packages/wiz-ui-react/src/components/base/inputs/selectbox/components/selectbox.tsx
packages/wiz-ui-react/src/components/base/inputs/upload/components/upload-display.tsx
packages/wiz-ui-react/src/components/base/stack/components/stack.tsx
packages/wiz-ui-react/src/components/base/stack/components/types.ts
packages/wiz-ui-react/src/components/base/stack/stories/h-stack.stories.tsx
packages/wiz-ui-react/src/components/base/stack/stories/stack.stories.tsx
packages/wiz-ui-react/src/components/base/stack/stories/v-stack.stories.tsx
packages/wiz-ui-react/src/components/base/tab/components/tab.tsx
packages/wiz-ui-react/src/components/custom/chat/components/chat-card.tsx
packages/wiz-ui-react/src/components/custom/chat/components/chat-form.tsx
packages/wiz-ui-react/src/components/custom/notification/components/notification-panel.tsx
packages/wiz-ui-react/src/components/custom/notification/stories/notification-list.stories.tsx
packages/wiz-ui-react/src/components/custom/notification/stories/notification-panel.stories.tsx

Refactor(stack): nowrapオプションを追加

---

.changeset/rare-elephants-enjoy.md
packages/wiz-ui-react/src/components/base/inputs/toggle-switch/components/toggle-switch.tsx

 ToggleSwitch に defaultColor 遠設定 (React)

---

.changeset/lucky-cycles-mate.md
packages/wiz-ui-react/src/components/base/menu/components/menu-item.tsx
packages/wiz-ui-react/src/components/base/menu/stories/menu-item.stories.tsx

Menu Item に fontSize Prop を追加  (React)

---

.changeset/chatty-beds-rescue.md
packages/styles/bases/show-more-less.css.ts
packages/wiz-ui-next/src/components/base/show-more-less/show-more-less.stories.ts
packages/wiz-ui-next/src/components/base/show-more-less/show-more-less.vue
packages/wiz-ui-react/src/components/base/show-more-less/components/show-more-less.tsx
packages/wiz-ui-react/src/components/base/show-more-less/stories/show-more-less.stories.tsx
packages/wiz-ui/src/components/base/show-more-less/show-more-less.stories.ts
packages/wiz-ui/src/components/base/show-more-less/show-more-less.vue

Feat(show-more-less): mobile用スタイルに対応

---

.changeset/dull-pandas-stare.md
packages/wiz-ui-react/src/components/base/dialog/components/dialog.tsx
packages/wiz-ui-react/src/components/base/dialog/stories/dialog.stories.tsx

Dialog に hideClose prop を追加 (React)

---

.changeset/rude-eggs-thank.md
packages/wiz-ui-react/src/components/base/popup/components/popup.tsx
packages/wiz-ui-react/src/components/base/popup/stories/fixed.tsx
packages/wiz-ui-react/src/components/base/popup/stories/popup.stories.tsx

resolve: #952
resolve: #953
resolve: #954 
resolve: #950

Feat(popup): vue版の変更に追従

---

.changeset/lemon-seals-invent.md
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.stories.ts
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui-react/src/components/base/inputs/selectbox/components/selectbox.tsx
packages/wiz-ui-react/src/components/base/inputs/selectbox/stories/selectbox.stories.tsx
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.stories.ts
packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.vue

feat(select-box): show exLabel

---

.changeset/lucky-kings-live.md
packages/wiz-ui-react/src/components/base/navigation/components/navigation-item.tsx
packages/wiz-ui-react/src/components/base/navigation/stories/navigation-container.stories.tsx

Feat(nav-item): toggle popupをオプショナルにする

---

.changeset/sour-balloons-raise.md
packages/styles/bases/circle-graph.css.ts

feat(circle-graph): 色を変更

---

.changeset/dull-mayflies-try.md
packages/wiz-ui-react/src/components/base/inputs/date-picker/components/date-picker.tsx

fix: date-pickerのbuttonのtypeを"button"に変更

---

packages/wiz-ui-next/src/components/base/card/card.vue
packages/wiz-ui-next/src/components/base/inputs/date-picker/date-picker.stories.ts
packages/wiz-ui-next/src/components/base/inputs/search-input/search-popup.vue
packages/wiz-ui/src/components/base/card/card.vue

前々から出ていた eslit warning を解消します。

eslint warning を解消

---

packages/wiz-ui-react/src/components/base/popup/test/popup-position.test.ts
packages/wiz-ui-react/src/components/base/popup/utils/popup-position.ts

VRT において Popup にランダムに差分が発生する状態になっているため、座標の小数点を丸めて様子を見ます。

chore: [React] popupの座標の小数点を丸める

---

.changeset/chatty-jars-smash.md
packages/constants/component/name.ts
packages/constants/styles/z-index.ts
packages/styles/bases/loading-overlay.css.ts
packages/wiz-ui-next/src/components/base/index.ts
packages/wiz-ui-next/src/components/base/loading-overlay/index.ts
packages/wiz-ui-next/src/components/base/loading-overlay/loading-overlay.stories.tsx
packages/wiz-ui-next/src/components/base/loading-overlay/loading-overlay.vue
packages/wiz-ui-react/src/components/base/index.ts
packages/wiz-ui-react/src/components/base/loading-overlay/components/index.ts
packages/wiz-ui-react/src/components/base/loading-overlay/components/loading-overlay.tsx
packages/wiz-ui-react/src/components/base/loading-overlay/index.ts
packages/wiz-ui-react/src/components/base/loading-overlay/stories/loading-overlay.stories.tsx
packages/wiz-ui/src/components/base/index.ts
packages/wiz-ui/src/components/base/loading-overlay/index.ts
packages/wiz-ui/src/components/base/loading-overlay/loading-overlay.stories.tsx
packages/wiz-ui/src/components/base/loading-overlay/loading-overlay.vue

feat: loading component

---

.changeset/selfish-panthers-matter.md
packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui/src/components/base/popup/popup.vue

Fix(popup): safariでfadeアニメーションが効かない問題を修正

---

.changeset/perfect-cooks-shave.md
packages/wiz-ui-next/src/components/base/tooltip/tooltip.stories.ts
packages/wiz-ui-next/src/components/base/tooltip/tooltip.vue
packages/wiz-ui-react/src/components/base/tooltip/components/tooltip.tsx
packages/wiz-ui-react/src/components/base/tooltip/stories/tooltip.stories.tsx
packages/wiz-ui/src/components/base/tooltip/tooltip.stories.ts
packages/wiz-ui/src/components/base/tooltip/tooltip.vue

Feat(Tooltip): hover → isOpenに変える

---

.changeset/ten-cats-tickle.md
packages/styles/bases/tab.css.ts
packages/wiz-ui-next/src/components/base/tab/tab-pane.stories.ts
packages/wiz-ui-next/src/components/base/tab/tab-pane.vue
packages/wiz-ui-react/src/components/base/tab/components/tab-pane.tsx
packages/wiz-ui-react/src/components/base/tab/stories/tab-pane.stories.tsx
packages/wiz-ui/src/components/base/tab/tab-pane.stories.ts
packages/wiz-ui/src/components/base/tab/tab-pane.vue

Feat(tab): badge color (緑/赤)を指定する機能を追加

---

.changeset/thick-cycles-kneel.md
packages/wiz-ui-react/src/components/base/inputs/search-selector/components/search-selector.tsx

fix: ReactのSearchSelectorにonInput追加

---

.changeset/tall-chefs-rest.md
packages/wiz-ui-react/src/components/base/calendar/components/calendar-helper.ts
packages/wiz-ui-react/src/components/base/calendar/components/calendar.tsx
packages/wiz-ui-react/src/components/base/calendar/components/types.ts
packages/wiz-ui-react/src/components/base/calendar/tests/calendar-helper.test.ts
packages/wiz-ui-react/src/components/base/inputs/date-picker/components/date-picker.tsx
packages/wiz-ui-react/src/components/base/inputs/date-picker/stories/date-picker.stories.tsx

Feat(date-picker, calender): 無効な日付を指定する機能のReact対応

---

.changeset/tasty-mayflies-pay.md
packages/styles/bases/snackbar.css.ts
packages/wiz-ui-next/src/components/base/snackbar/snackbar-controller.vue
packages/wiz-ui-next/src/components/base/snackbar/snackbar.stories.ts
packages/wiz-ui-next/src/components/base/snackbar/snackbar.vue
packages/wiz-ui-next/src/components/base/snackbar/types.ts
packages/wiz-ui-next/src/hooks/use-snackbar.ts
packages/wiz-ui-react/src/components/base/snackbar/components/snackbar-context.tsx
packages/wiz-ui-react/src/components/base/snackbar/components/snackbar-provider.tsx
packages/wiz-ui-react/src/components/base/snackbar/components/snackbar.tsx
packages/wiz-ui-react/src/components/base/snackbar/stories/snackbar.stories.tsx
packages/wiz-ui/src/components/base/snackbar/snackbar-controller.vue
packages/wiz-ui/src/components/base/snackbar/snackbar.stories.ts
packages/wiz-ui/src/components/base/snackbar/snackbar.vue
packages/wiz-ui/src/components/base/snackbar/types.ts
packages/wiz-ui/src/hooks/use-snackbar.ts

Snackbar に expand Property を追加

---

packages/wiz-ui/package.json

ci(vrt): remove vue2 vrt

---

.changeset/lemon-guests-kneel.md
packages/constants/component/name.ts
packages/styles/bases/radio-new.css.ts
packages/wiz-ui-next/src/components/base/inputs/index.ts
packages/wiz-ui-next/src/components/base/inputs/radio-new/index.ts
packages/wiz-ui-next/src/components/base/inputs/radio-new/radio-new.stories.ts
packages/wiz-ui-next/src/components/base/inputs/radio-new/radio-new.vue
packages/wiz-ui-next/src/components/base/inputs/radio/index.ts
packages/wiz-ui-react/src/components/base/inputs/index.ts
packages/wiz-ui-react/src/components/base/inputs/radio-new/components/index.ts
packages/wiz-ui-react/src/components/base/inputs/radio-new/components/radio-new.tsx
packages/wiz-ui-react/src/components/base/inputs/radio-new/index.ts
packages/wiz-ui-react/src/components/base/inputs/radio-new/stories/radio-new.stories.tsx
packages/wiz-ui-react/src/components/base/inputs/radio/components/radio.tsx

resolve: #1028 
* `WizRadioNew` コンポーネントとして追加
* 既存の `WizRadio` コンポーネントを deprecated

WizRadioNew コンポーネントを追加

---

.changeset/green-stingrays-sing.md
packages/wiz-ui-react/src/components/custom/notification/components/notification-panel.tsx
packages/wiz-ui-react/src/components/custom/notification/stories/notification-panel.stories.tsx

[#989] Notification Panel デザイン修正 (React)

---

.changeset/modern-windows-sip.md
packages/wiz-ui-react/src/components/base/popup/components/popup.tsx

[#979] Popup:  Fade in out のバグ修正（React）

---

.changeset/smooth-drinks-sniff.md
packages/styles/bases/search-selector.css.ts
packages/wiz-ui-next/src/components/base/inputs/search-selector/search-selector.stories.ts
packages/wiz-ui-react/src/components/base/inputs/search-selector/stories/search-selector.stories.tsx

resolve: #1055
lineHeightをfigmaの仕様に合わせました: 17px

Fix(search-selector): lineHeight

---

packages/wiz-ui/package.json
pnpm-lock.yaml

chore(deps): wiz-ui-vue2の依存関係を固定

---

packages/wiz-ui/package.json
pnpm-lock.yaml

Reverts Wizleap-Inc/wiz-ui#1083

Revert "chore(deps): wiz-ui-vue2の依存関係を固定"

---

.changeset/strange-bottles-camp.md
packages/styles/bases/full-modal-view.css.ts
packages/wiz-ui-next/src/components/base/full-modal-view/full-modal-view.stories.ts
packages/wiz-ui-next/src/components/base/full-modal-view/full-modal-view.vue
packages/wiz-ui-react/src/components/base/full-modal-view/components/full-modal-view.tsx
packages/wiz-ui-react/src/components/base/full-modal-view/components/index.ts
packages/wiz-ui-react/src/components/base/full-modal-view/index.ts
packages/wiz-ui-react/src/components/base/full-modal-view/stories/full-modal-view.stories.tsx

Feat(full modal view): react対応

---

.changeset/mighty-moles-tease.md

resolve: #1101
d0aea53 で解決（ブランチ切っていたと思ったらmainに直pushしていました……すみません…… 🙇 ）

Bug(text): "webkitBoxOrient" の "w" が大文字になっておらずエラーが出る

---

packages/styles/bases/checkbox-new.css.ts
packages/styles/bases/radio-new.css.ts

fix: NewCheckboxとNewRadioのスタイル修正

---

.changeset/popular-clouds-accept.md
packages/styles/bases/checkbox-new.css.ts
packages/styles/bases/search-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui-next/src/components/base/inputs/search-input/search-popup.vue
packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-popup-panel.tsx

Chore(search-input): WizCheckboxNewに差し替える

---

.changeset/nasty-donuts-shave.md
packages/styles/bases/toggle-switch-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/toggle-switch/toggle-switch.stories.ts
packages/wiz-ui-next/src/components/base/inputs/toggle-switch/toggle-switch.vue
packages/wiz-ui-react/src/components/base/inputs/toggle-switch/components/toggle-switch.tsx
packages/wiz-ui-react/src/components/base/inputs/toggle-switch/stories/toggle-switch.stories.tsx

Feat(toggle-switch): 新デザイン対応

---

.changeset/wet-rocks-wave.md
packages/styles/bases/text-button.css.ts
packages/wiz-ui-next/src/components/base/buttons/text/text.stories.ts
packages/wiz-ui-next/src/components/base/buttons/text/text.vue
packages/wiz-ui-react/src/components/base/buttons/text/components/text-button.tsx
packages/wiz-ui-react/src/components/base/buttons/text/stories/text-button.stories.tsx

Feat(text-button): danger, sub-danger variantを追加

---

.changeset/silly-cooks-applaud.md
packages/wiz-ui-next/src/components/base/navigation/container.stories.ts
packages/wiz-ui-next/src/components/base/navigation/container.vue
packages/wiz-ui-react/src/components/base/navigation/components/navigation-container.tsx
packages/wiz-ui-react/src/components/base/navigation/stories/navigation-container.stories.tsx

resolve: #1130
- Vue, React で、width を設定しても isOpen が変更できるように修正
- Width の Story 追加
- Storybook の navigation に background-color を追加
https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/48b30929-cd73-4e20-9127-1012c822d149

NavigationContainerで任意のwidthを指定したい

---

.changeset/big-tables-retire.md
packages/wiz-ui-next/src/components/custom/timeline/stories/timeline-item.stories.ts
packages/wiz-ui-next/src/components/custom/timeline/timeline-item.vue
packages/wiz-ui-react/src/components/custom/timeline/components/timeline-item.tsx
packages/wiz-ui-react/src/components/custom/timeline/stories/timeline-item.stories.tsx

Feat(timeline): iconを差し替えられるようにする

---

.changeset/tough-bobcats-cough.md
packages/wiz-ui-next/src/components/base/information-panel/information-panel.stories.ts
packages/wiz-ui-next/src/components/base/information-panel/information-panel.vue
packages/wiz-ui-react/src/components/base/information-panel/components/information-panel.tsx
packages/wiz-ui-react/src/components/base/information-panel/stories/information-panel.stories.tsx

Feat(information-panel): リンクを表示できるようにする

---

.changeset/strange-scissors-beam.md
packages/wiz-ui-next/src/components/base/information-panel/information-panel.stories.ts
packages/wiz-ui-next/src/components/base/information-panel/information-panel.vue

Fix(information-panel): コンポーネントを受け付ける型を修正 & storyのバグ修正

---

.changeset/brave-hornets-promise.md
packages/styles/bases/checkbox-new.css.ts
packages/styles/bases/radio-new.css.ts
packages/wiz-ui-next/src/components/base/inputs/checkbox-new/checkbox-new.stories.ts
packages/wiz-ui-next/src/components/base/inputs/checkbox-new/checkbox-new.vue
packages/wiz-ui-next/src/components/base/inputs/radio-new/radio-new.stories.ts
packages/wiz-ui-next/src/components/base/inputs/radio-new/radio-new.vue
packages/wiz-ui-react/src/components/base/inputs/checkbox-new/components/checkbox-new.tsx
packages/wiz-ui-react/src/components/base/inputs/checkbox-new/stories/checkbox-new.stories.tsx
packages/wiz-ui-react/src/components/base/inputs/radio-new/components/radio-new.tsx
packages/wiz-ui-react/src/components/base/inputs/radio-new/stories/radio-new.stories.tsx

resolve: #1139 
- Storybook にて、複数行のケースを追加
- Checkbox, Radio コンポーネントの入力位置の修正

(checkbox-new, radio-new): チェックボックスとラベルの複数行でのInput の位置を修正

---

.changeset/ninety-rocks-heal.md
packages/styles/bases/text-button.css.ts
packages/wiz-ui-next/src/components/base/buttons/text/text.stories.ts
packages/wiz-ui-next/src/components/base/buttons/text/text.vue
packages/wiz-ui-react/src/components/base/buttons/text/components/text-button.tsx
packages/wiz-ui-react/src/components/base/buttons/text/stories/text-button.stories.tsx

resolve: #1193
- Text Button の variant に "gray" を追加

Feat(text-button): 新しいvariant: grayを追加する

---

.changeset/cool-knives-play.md
packages/wiz-ui-next/src/components/base/avatar/avatar.stories.ts
packages/wiz-ui-next/src/components/base/avatar/avatar.vue
packages/wiz-ui-react/src/components/base/avatar/components/avatar.tsx
packages/wiz-ui-react/src/components/base/avatar/stories/avatar.stories.tsx

resolve: #1137
https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/86bc6fae-586b-4acb-b9cf-c4cfb4c90417

[#1137] Avatar の bgColor を random で生成されるように修正

---

.changeset/light-planes-talk.md
packages/styles/bases/line-graph.css.ts
packages/wiz-ui-next/src/components/base/graphs/line/line.stories.ts
packages/wiz-ui-next/src/components/base/graphs/line/line.vue
packages/wiz-ui-react/src/components/base/graphs/line/components/line-graph.tsx
packages/wiz-ui-react/src/components/base/graphs/line/stories/line-graph.stories.tsx

Feat(line-graph): 背景を非表示にする機能の実装 #1205

---

.changeset/tasty-ads-listen.md
packages/wiz-ui-next/src/components/base/avatar/avatar.vue
packages/wiz-ui-react/src/components/base/avatar/components/avatar.tsx

fix(avatar): srcがundefinedの場合はimgタグを表示しない

---

.changeset/seven-carrots-sparkle.md
packages/styles/bases/base-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/base/base.vue
packages/wiz-ui-react/src/components/base/inputs/base/components/base-input.tsx

base-inputのFocusの色をデフォルトのものにする

---

.changeset/kind-cars-sneeze.md
packages/wiz-ui-react/src/components/custom/form/components/form-control.tsx

Fix(form-control): エラーメッセージ表示によるレイアウトシフト発生を防ぐ

---

.changeset/moody-fishes-ring.md
packages/wiz-ui-react/src/components/base/popup/components/popup.tsx

fix: ポップアップの座標計算修正（React）

---

.changeset/new-ants-worry.md
packages/wiz-ui-next/src/components/base/popup/popup.vue

fix: ポップアップの座標計算修正（vue）

---

packages/icons/package.json

chore: node + loaderを使ったビルド方法に変更

---

.changeset/breezy-numbers-march.md
packages/wiz-ui-next/src/components/base/inputs/date-range-picker/date-range-picker.vue
packages/wiz-ui-react/src/components/base/inputs/date-range-picker/components/date-range-picker.tsx

fix: DateRangePickerのdisableDateが左側カレンダーにも反映されるように修正

---

.changeset/tricky-jokes-film.md
packages/wiz-ui-next/src/components/base/graphs/poll/poll.stories.ts
packages/wiz-ui-react/src/components/base/graphs/poll/components/bar.tsx
packages/wiz-ui-react/src/components/base/graphs/poll/stories/poll-graph.stories.tsx

Fix(poll-graph): 0%での表示がVue・Reactで異なる問題を修正

---

.changeset/big-rings-raise.md
.changeset/gold-weeks-enjoy.md
packages/wiz-ui-react/src/components/custom/chat/components/chat-card.tsx
packages/wiz-ui-react/src/components/custom/chat/stories/chat-card.stories.tsx

Feat(chat-card): 開閉状態を指定可能にする

---

.changeset/blue-squids-occur.md
packages/wiz-ui-react/src/components/base/navigation/components/navigation-item.tsx
packages/wiz-ui-react/src/components/base/navigation/stories/navigation-item.stories.tsx

Feat(nav-item): 外部リンクを別タブで開く

---

.changeset/clever-turtles-visit.md
packages/wiz-ui-react/src/components/base/buttons/text/components/text-button.tsx

Fix(text-button): button内のコンテンツが回り込む問題を修正

---

packages/wiz-ui-react/.storybook/main.js

fix(storybook): reference error

---

.changeset/pretty-trains-lay.md
packages/styles/bases/search-selector.css.ts
packages/wiz-ui-next/src/components/base/inputs/search-selector/search-selector.vue

Fix(search-selector): disabled時に選択解除可能な問題を修正

---

package.json
packages/wiz-ui-next/.storybook/main.js
pnpm-lock.yaml

cd(storybook): reference error

---

packages/wiz-ui-react/src/components/base/inputs/date-range-picker/stories/date-range-picker.stories.tsx

docs(date-range-picker): 月初にVRTが落ちる問題を修正

---

.changeset/itchy-carrots-design.md
packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui-next/src/components/base/inputs/search-input/stories/options.ts
packages/wiz-ui-next/src/components/base/inputs/search-input/stories/search-input.stories.ts
packages/wiz-ui-next/src/components/base/inputs/search-input/types.ts
packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-input.tsx
packages/wiz-ui-react/src/components/base/inputs/search-input/components/types.ts
packages/wiz-ui-react/src/components/base/inputs/search-input/stories/dummy-data.ts
packages/wiz-ui-react/src/components/base/inputs/search-input/stories/search-input.stories.tsx

feat(search-input): 選択した要素のアイテムの親階層がわかるようにする

---

.changeset/itchy-carrots-design.md
packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui-next/src/components/base/inputs/search-input/stories/options.ts
packages/wiz-ui-next/src/components/base/inputs/search-input/stories/search-input.stories.ts
packages/wiz-ui-next/src/components/base/inputs/search-input/types.ts
packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-input.tsx
packages/wiz-ui-react/src/components/base/inputs/search-input/components/types.ts
packages/wiz-ui-react/src/components/base/inputs/search-input/stories/dummy-data.ts
packages/wiz-ui-react/src/components/base/inputs/search-input/stories/search-input.stories.tsx

Reverts Wizleap-Inc/wiz-ui#1331

Revert "feat(search-input): 選択した要素のアイテムの親階層がわかるようにする"

---

.changeset/tender-impalas-repair.md
packages/styles/bases/radio-new.css.ts

Fix(radio-new): disabled時にcursor: not-allowedを適用する

---

.changeset/smart-zoos-fly.md
packages/wiz-ui-react/src/components/base/inputs/search-selector/components/search-selector-helper.ts
packages/wiz-ui-react/src/components/base/inputs/search-selector/components/search-selector.tsx

Feat(search-selector): 検索機能を改善

---

.changeset/many-months-deliver.md
packages/styles/bases/search-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-input.tsx

Fix(search-input): バグ修正

---

packages/wiz-ui-next/src/components/base/anchor/anchor.stories.ts
packages/wiz-ui-react/src/components/base/anchor/stories/anchor.stories.tsx

docs(anchor): onClick

---

.changeset/tame-ways-admire.md
packages/wiz-ui-react/src/components/base/navigation/components/navigation-item.tsx
packages/wiz-ui-react/src/components/base/navigation/stories/navigation-item.stories.tsx

feat(nav-item): hrefを任意プロパティに変更する

---

.changeset/six-queens-tickle.md
examples/vue3/src/pages/chat/_components/chat-form.vue
package.json
pnpm-lock.yaml

ジェネリクスの型がうまく生成できない問題の解消

---

packages/wiz-ui-next/.storybook/preview.js
packages/wiz-ui-react/.storybook/preview.js

fix: VRTの画面サイズをviewportで固定

---

.changeset/soft-rivers-count.md
packages/styles/customs/timeline.css.ts
packages/wiz-ui-next/src/components/custom/timeline/stories/timeline-item.stories.ts
packages/wiz-ui-next/src/components/custom/timeline/timeline-item.vue
packages/wiz-ui-react/src/components/custom/timeline/components/timeline-item.tsx
packages/wiz-ui-react/src/components/custom/timeline/stories/timeline-item.stories.tsx

Feat(timeline-item): gray background

---

.changeset/cool-tools-relax.md
packages/styles/bases/number-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/number-input/number-input.vue
packages/wiz-ui-react/src/components/base/inputs/number-input/components/number-input.tsx

Fix(number-input): disabled style

---

.github/ISSUE_TEMPLATE/機能追加（アイコン）.md

docs: new icon issue template

---

.changeset/moody-rules-love.md
.github/workflows/build-check.yml
.github/workflows/bundle-analyze.yml
.github/workflows/lint.yml
.github/workflows/publish-library.yml
.github/workflows/test.yml
.github/workflows/visual-regression-test.yml
packages/styles/customs/timeline.css.ts
packages/wiz-ui-next/src/components/icons/index.ts
packages/wiz-ui-react/src/components/custom/timeline/components/timeline-item.tsx
packages/wiz-ui-react/src/components/icons/index.ts

Feat(TimelineItem): disabled のスタイルの変更

---

.changeset/poor-points-drum.md
examples/vue3/src/pages/chat/_components/chat-form.vue
packages/constants/styles/border-width.ts
packages/constants/styles/index.ts
packages/styles/bases/calendar.css.ts
packages/styles/bases/card-table.css.ts
packages/styles/bases/checkbox-input.css.ts
packages/styles/bases/checkbox-new.css.ts
packages/styles/bases/compare-graph.css.ts
packages/styles/bases/date-range-picker.css.ts
packages/styles/bases/flat-table.css.ts
packages/styles/bases/full-modal-view.css.ts
packages/styles/bases/information-panel.css.ts
packages/styles/bases/message-box.css.ts
packages/styles/bases/number-input.css.ts
packages/styles/bases/panel-switch-input.css.ts
packages/styles/bases/radio-input.css.ts
packages/styles/bases/search-input.css.ts
packages/styles/bases/search-selector.css.ts
packages/styles/bases/tag.css.ts
packages/styles/bases/transition-graph.css.ts
packages/styles/bases/unstyled-table.css.ts
packages/styles/customs/schedule.css.ts
packages/styles/customs/timeline.css.ts
packages/wiz-ui-next/src/components/base/navigation/container.vue
packages/wiz-ui-react/src/components/base/navigation/components/navigation-container.tsx

resolve: #[1444]
changeset周りが自信ないので確認お願いします。

borderの太さを定数（xs, sm, md, lg）としてconstantsに追加

---

.husky/pre-commit
package.json
pnpm-lock.yaml

chore(deps): update husky

---

.changeset/tasty-emus-ring.md
packages/wiz-ui-next/src/components/custom/form/control.stories.ts
packages/wiz-ui-next/src/components/custom/form/control.vue
packages/wiz-ui-react/src/components/custom/form/components/form-control.tsx
packages/wiz-ui-react/src/components/custom/form/stories/form-control.stories.tsx

feat(form-control): label suffix

---

.changeset/loud-eggs-juggle.md
packages/styles/bases/card.css.ts
packages/wiz-ui-next/src/components/base/card/card.stories.ts
packages/wiz-ui-next/src/components/base/card/card.vue
packages/wiz-ui-react/src/components/base/card/components/card.tsx
packages/wiz-ui-react/src/components/base/card/stories/card.stories.tsx

Feat(card): border color

---

.changeset/soft-pans-build.md
packages/styles/bases/tag.css.ts
packages/wiz-ui-next/src/components/base/tag/tag.stories.ts
packages/wiz-ui-next/src/components/base/tag/tag.vue
packages/wiz-ui-react/src/components/base/tag/components/tag.tsx
packages/wiz-ui-react/src/components/base/tag/stories/tag.stories.tsx

Feat(tag): redFill

---

.changeset/bumpy-melons-itch.md
packages/styles/bases/menu.css.ts
packages/wiz-ui-next/src/components/base/menu/menu-item.stories.ts
packages/wiz-ui-next/src/components/base/menu/menu-item.vue
packages/wiz-ui-next/src/components/base/tag/tag.vue
packages/wiz-ui-next/src/components/base/tag/types.ts
packages/wiz-ui-react/src/components/base/menu/components/menu-item.tsx
packages/wiz-ui-react/src/components/base/menu/stories/menu-item.stories.tsx
packages/wiz-ui-react/src/components/base/tag/components/tag.tsx
packages/wiz-ui-react/src/components/base/tag/types/index.ts
packages/wiz-ui-react/src/components/base/tag/types/variant.ts

Feat(MenuItem): タグを追加できるように

---

.changeset/fluffy-ravens-switch.md
packages/styles/bases/card.css.ts
packages/wiz-ui-next/src/components/base/card/card.vue
packages/wiz-ui-react/src/components/base/card/components/card.tsx

feat: wiz-cardにhexpandプロパティを追加

---

.changeset/poor-moons-jam.md
packages/styles/bases/menu.css.ts
packages/wiz-ui-next/src/components/base/menu/menu-item.stories.ts
packages/wiz-ui-next/src/components/base/menu/menu-item.vue
packages/wiz-ui-react/src/components/base/menu/components/menu-item.tsx
packages/wiz-ui-react/src/components/base/menu/stories/menu-item.stories.tsx

Feat(menu-item): アイコン表示・シェブロン削除対応

---

.changeset/public-owls-stay.md

chore: changeset

---

.changeset/mean-kings-learn.md
packages/styles/bases/icon-button.css.ts
packages/wiz-ui-next/src/components/base/buttons/icon/icon.stories.ts
packages/wiz-ui-next/src/components/base/buttons/icon/icon.vue
packages/wiz-ui-react/src/components/base/buttons/icon/components/icon-button.tsx
packages/wiz-ui-react/src/components/base/buttons/icon/stories/icon-button.stories.tsx

feat: Feat(WizIconButton): variant=whiteの追加

---

.changeset/calm-waves-start.md
packages/wiz-ui-react/src/components/custom/voice-input/components/voice-input.tsx

fix(voice-input): on-changeをoptionalにする
