Wizleap-Inc/wiz-ui

packages/styles/commons/gap.css.ts

fix:wiz-stackでgxとgyを両方指定した際にgxが効かないバグの修正

---

packages/wiz-ui-next/src/components/base/inputs/search-selector/levenshtein-distance.ts
packages/wiz-ui/src/components/base/inputs/search-selector/levenshtein-distance.ts

resolve: #433
検索に用いられたアルゴリズムで、For 文での調査範囲が間違っていたので修正した。
...|before|after
---|---|---
動作|<video src="https://user-images.githubusercontent.com/29594820/224116033-30244099-ee43-4c4d-94b0-059c2dffd355.mov"/>|<video src="https://user-images.githubusercontent.com/29594820/224115864-491e90d8-e979-4d9d-8064-4b49648fa6f8.mov"/>
精度(20 を検索した場合)|![スクリーンショット 2023-03-10 1 47 12](https://user-images.githubusercontent.com/29594820/224094604-4ea44016-3d65-49d5-9fd7-2ea9e67c34b6.png)|![スクリーンショット 2023-03-10 2 34 58](https://user-images.githubusercontent.com/29594820/224109254-58611522-e652-44f6-bde4-d598272562b2.png)

[#433] 検索精度の向上

---

.changeset/cold-drinks-rhyme.md
packages/wiz-ui/src/components/base/tooltip/tooltip.vue

resolve #661 
Tooltip で gap の定義が wiz-ui と　wiz-ui-next とで異なっていたため、Slack にて相談ののち、 `xs2` に統一した。
https://wizleap.slack.com/archives/C03UB1CL2LS/p1681994105252749

Tooltip の Gap を統一

---

.eslintrc.react.json
package.json
packages/wiz-ui-react/src/components/base/stack/stories/h-stack.stories.tsx
packages/wiz-ui-react/src/components/base/stack/stories/stack.stories.tsx
packages/wiz-ui-react/src/components/base/stack/stories/v-stack.stories.tsx
pnpm-lock.yaml

React hooks を書く上でこのlintが効かないと結構大変だと思うので追加しました。
FYI: https://ja.legacy.reactjs.org/docs/hooks-rules.html#eslint-plugin

chore: eslint-plugin-react-hooks を設定

---

.changeset/sixty-grapes-retire.md
packages/styles/bases/menu.css.ts
packages/styles/bases/navigation.css.ts

resolve: #677
グローバルナビとサブメニューの高さを44pxにしました。
対象コンポーネント
* navigation-item http://localhost:6007/?path=/docs/base-navigation-item--docs
* menu-item http://localhost:6007/?path=/docs/base-menuitem--docs

Feat: グローバルナビとサブメニューの高さを44pxにする

---

.changeset/early-apples-eat.md
packages/styles/bases/base-input.css.ts
packages/styles/bases/date-picker-input.css.ts
packages/styles/bases/date-range-picker.css.ts
packages/styles/bases/search-input.css.ts
packages/styles/bases/search-selector.css.ts
packages/styles/bases/selectbox-input.css.ts
packages/styles/bases/text-button.css.ts
packages/styles/bases/time-picker-input.css.ts
packages/styles/bases/toggle-button.css.ts

resolve: #712
フォームに関連するコンポーネントの高さを44pxに統一しました。
* text-input
* password-input
* select-box
* date-picker
* date-range-picker
* time-picker
* search-selector
* search
sm: 36px
md: 40px
lg: 44px
※ https://github.com/Wizleap-Inc/wiz-ui/issues/772 のissueをこちらのPRにまとめました。

Feat: フォームに関連するコンポーネントの高さを44pxに統一

---

.changeset/shiny-apricots-complain.md
packages/wiz-ui-next/src/components/custom/form/control.vue
packages/wiz-ui-next/src/components/custom/form/group.stories.ts
packages/wiz-ui-next/src/components/custom/form/group.vue
packages/wiz-ui-next/src/hooks/use-form-group-provider.ts
packages/wiz-ui/src/components/custom/form/control.vue
packages/wiz-ui/src/components/custom/form/group.stories.ts
packages/wiz-ui/src/components/custom/form/group.vue
packages/wiz-ui/src/hooks/use-form-group-provider.ts

resolve: #756
WizFormGroupでラベルのサイズと色を一括指定できるようにしました。
vue: http://localhost:6006/?path=/docs/custom-form-group--docs
vue_next: http://localhost:6007/?path=/docs/custom-form-group--docs

Feat: WizFormGroupでラベルのサイズと色を一括指定できるようにする

---

.changeset/shiny-wolves-shop.md
packages/wiz-ui-react/src/components/base/graphs/index.ts
packages/wiz-ui-react/src/components/base/graphs/transition/components/bar.tsx
packages/wiz-ui-react/src/components/base/graphs/transition/components/index.ts
packages/wiz-ui-react/src/components/base/graphs/transition/components/transition-graph.tsx
packages/wiz-ui-react/src/components/base/graphs/transition/index.ts
packages/wiz-ui-react/src/components/base/graphs/transition/stories/transition-graph.stories.tsx
packages/wiz-ui-react/src/components/base/index.ts

resolve: #812 
* 追加対応
* 各バー内のラベルについて、`padding` を編集しながら `offsetHeight` を参照するのは予期せぬ挙動に繋がりそうだったので、`padding` はいじらずに `top` か `bottom` のみで位置を調整するように変更
* 各バーにおいて、`isFIrst` ではなく `lastFrequency` の有無によって表示を切り替えるように変更
* 何もしていない要素を削除

WizTransitionGraphのReact対応

---

.changeset/tiny-doors-warn.md
packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui/src/components/base/popup/popup.vue

resolve:  #615 
- https://qiita.com/siy1121/items/d5a5f198744cf882ef02#%E6%96%B9%E6%B3%95%EF%BC%91 
この記事の参照を元に、`translateZ(0)` を追加するとバグが解消されることを確認

Popup で影が残るバグを修正

---

.changeset/tender-toes-speak.md
packages/wiz-ui-react/src/components/base/popup/components/popup.tsx
packages/wiz-ui-react/src/components/base/popup/test/wrap.test.ts
packages/wiz-ui-react/src/components/base/popup/utils/wrap.ts
packages/wiz-ui-react/src/components/base/stack/stories/h-stack.stories.tsx
packages/wiz-ui-react/src/components/base/stack/stories/stack.stories.tsx
packages/wiz-ui-react/src/components/base/stack/stories/v-stack.stories.tsx

* React 版の Popup で、全体の高さを `document.body` から取得していた関係で、storybook などで body 自体が小さいときに意図せず回り込みが効いてしまう場合があったので、全体の高さを `document.body.clientHeight` と `widnow.innerHeight` のうちの大きい方を採用するように変更
* `any` 型を使っている部分を修正

fix: [React] いくつかの微修正

---

.changeset/rare-cameras-raise.md
packages/wiz-ui-next/src/components/base/inputs/search-selector/search-selector.vue
packages/wiz-ui/src/components/base/inputs/search-selector/search-selector.vue

resolve: #793
仕様について特に書かれていなかったので、レーベンシュタイン距離で最も近い文字のみを抽出するように実装した。これでは、2 番目に近い文字などを検索することが難しくなると思われるため、二番目に近いものも抽出できるようにしたほうがいいかもしれないので、動作時のレビューをお願いします。

WizSearchSelector : 検索時に該当した文字のみ抽出

---

.changeset/four-sheep-check.md
packages/wiz-ui-react/src/components/base/inputs/index.ts
packages/wiz-ui-react/src/components/base/inputs/search-selector/components/index.ts
packages/wiz-ui-react/src/components/base/inputs/search-selector/components/search-selector-helper.ts
packages/wiz-ui-react/src/components/base/inputs/search-selector/components/search-selector.tsx
packages/wiz-ui-react/src/components/base/inputs/search-selector/components/types.ts
packages/wiz-ui-react/src/components/base/inputs/search-selector/index.ts
packages/wiz-ui-react/src/components/base/inputs/search-selector/stories/search-selector.stories.tsx
packages/wiz-ui-react/src/components/base/popup/components/popup.tsx

resolve: #866 
* 追加対応
* `WizPopup` において、`anchorElement` のリサイズ時にも位置が再計算されるように修正

feat: WizSearchSelectorのReact対応

---

.changeset/friendly-experts-doubt.md
packages/wiz-ui-next/src/components/base/inputs/date-range-picker/date-range-picker.vue
packages/wiz-ui/src/components/base/inputs/date-range-picker/date-range-picker.vue

resolve: #976
- e.preventDefault() を追加して左右にスクロールしないように修正した 
https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/3392de1b-0540-4ba9-bd4f-8203b810fe13

[#976] 左右のキーボードを押したときにスクロールがおまけで付いてくるバグの修正

---

.changeset/dull-gifts-do.md
packages/styles/bases/card-table.css.ts
packages/wiz-ui-next/src/components/base/tables/card/hooks/use-is-safari.ts
packages/wiz-ui-next/src/components/base/tables/card/table.stories.ts
packages/wiz-ui-next/src/components/base/tables/card/table.vue
packages/wiz-ui-next/src/components/base/tables/card/td.vue
packages/wiz-ui-next/src/components/base/tables/card/th.vue
packages/wiz-ui-next/src/components/base/tables/card/tr.vue
packages/wiz-ui-react/src/components/base/tables/card/components/card-table.tsx
packages/wiz-ui-react/src/components/base/tables/card/components/card-td.tsx
packages/wiz-ui-react/src/components/base/tables/card/components/card-th.tsx
packages/wiz-ui-react/src/components/base/tables/card/components/card-tr.tsx
packages/wiz-ui-react/src/components/base/tables/card/hooks/use-is-safari.ts
packages/wiz-ui/src/components/base/tables/card/hooks/use-is-safari.ts
packages/wiz-ui/src/components/base/tables/card/table.vue
packages/wiz-ui/src/components/base/tables/card/td.vue
packages/wiz-ui/src/components/base/tables/card/th.vue
packages/wiz-ui/src/components/base/tables/card/tr.vue

resolve: #617
- Safari 用に :hover 時の td, tr タグの CSS を追加した。
- Safari での hover 時の border を outline で表示するようにした
- テーブル外でも hover が効いてしまうバグがのこっていること 
- Safari での border の出し方を変えてしまっているためこれでいいかどうかの確認が必要なこと
https://github.com/Wizleap-Inc/wiz-ui/assets/29594820/88174cab-c53f-4e63-ac62-3bef3f51879f
- Safari では、tr タグ要素に :after といった疑似要素が適用できないようです。

card table  での hover のバグ修正

---

.changeset/stupid-ants-provide.md
packages/wiz-ui-react/src/components/base/inputs/radio/components/radio.tsx

resolve: #957 
- Radio ボタンにフォーカスされたら矢印キーで選択できるようにする

Radio ボタンの a11y 化 (React)

---

.eslintrc.react.json
packages/wiz-ui-react/src/components/base/buttons/.eslintrc.json
packages/wiz-ui-react/src/components/base/calendar/components/calendar.tsx
packages/wiz-ui-react/src/components/base/dropdown/components/dropdown-item.tsx
packages/wiz-ui-react/src/components/base/inputs/date-picker/components/date-picker.tsx
packages/wiz-ui-react/src/components/base/inputs/date-range-picker/components/date-range-picker.tsx
packages/wiz-ui-react/src/components/base/inputs/password/components/password-input.tsx
packages/wiz-ui-react/src/components/base/inputs/search-selector/components/search-selector.tsx
packages/wiz-ui-react/src/components/base/inputs/time-picker/components/time-picker.tsx
packages/wiz-ui-react/src/components/base/snackbar/components/snackbar.tsx
packages/wiz-ui-react/src/components/custom/chat/components/chat-card.tsx
packages/wiz-ui-react/src/components/custom/schedule/components/card.tsx

button 要素は type を指定しなかったとき既定値で `type="submit"` となり、Form 要素内にある submit button が押下されると form が submit されてしまい UI ライブラリとしては具合が悪いので、button 要素に対する type 指定漏れを検知する lint ルールを追加し、対象となるコンポーネントに適用します。
ただし、以下のコンポーネントは lint ルールの対象外としています。
* `base/buttons` 配下のコンポーネント
* これらのコンポーネントは Props で与えられた `type` を button 要素に受け渡すだけで、明示的に `type` を指定しないため
* Story 関連のファイル
* 今回対象としたいのは公開するコンポーネントのみなため
また、各コンポーネントに付与する `type` として、`submit` を想定しているコンポーネントは存在しないと思われるので全て `type="button"` を指定しています。

fix: button要素にtypeを付与

---

.changeset/breezy-seas-walk.md
packages/wiz-ui-react/src/components/base/inputs/date-picker/components/date-picker.tsx
packages/wiz-ui-react/src/components/base/inputs/date-range-picker/components/date-range-picker.tsx

resolve: #965
- React のキーボード操作追加
- React の `date-range-picker` にて、onClick 時に true で開いたままになっていたのでこのバグを修正した

Date Picker, Data Range Picker のキーボード対応追加 (React)

---

packages/wiz-ui-react/src/components/base/snackbar/components/snackbar-provider.tsx

DOM の順番の関係で Snackbar と NavigationContainer が重なって表示された場合、Snackbar が下側に表示されるのを修正します。

[React] fix: snackbarが他の要素の下側表示にならないようにDOM構造を変更

---

.changeset/olive-dingos-jam.md
packages/constants/component/name.ts
packages/styles/bases/checkbox-new.css.ts
packages/wiz-ui-next/src/components/base/inputs/checkbox-new/checkbox-new.stories.ts
packages/wiz-ui-next/src/components/base/inputs/checkbox-new/checkbox-new.vue
packages/wiz-ui-next/src/components/base/inputs/checkbox-new/index.ts
packages/wiz-ui-next/src/components/base/inputs/checkbox/index.ts
packages/wiz-ui-next/src/components/base/inputs/index.ts
packages/wiz-ui-react/src/components/base/inputs/checkbox-new/components/checkbox-new.tsx
packages/wiz-ui-react/src/components/base/inputs/checkbox-new/components/index.ts
packages/wiz-ui-react/src/components/base/inputs/checkbox-new/index.ts
packages/wiz-ui-react/src/components/base/inputs/checkbox-new/stories/checkbox-new.stories.tsx
packages/wiz-ui-react/src/components/base/inputs/checkbox/components/checkbox.tsx
packages/wiz-ui-react/src/components/base/inputs/index.ts

resolve: #1027 
* 新しいチェックボックを `WizCheckBoxNew` として追加
* コンポーネントとしてはグループ化されている必要はないので単体のチェックボックスとして実装
* 既存の `WizCheckBox` を deprecated
* Vue 版はやり方が不明だったので React 版のみ

WizCheckBoxNew コンポーネントを追加

---

.changeset/loud-otters-perform.md
packages/styles/customs/timeline.css.ts

resolve: #1164
次のようにして、アイコンを線より手前に表示することで修正
- 線のz-index設定を削除
- アイコンのz-indexを1

Fix(timeline): アイテムを繋ぐ線が、背景より奥にある問題を修正

---

.changeset/slow-insects-enjoy.md
packages/wiz-ui-next/src/components/base/inputs/base/base.vue
packages/wiz-ui-next/src/components/base/inputs/password/password.vue
packages/wiz-ui-next/src/components/base/inputs/text/text.vue
packages/wiz-ui-react/src/components/base/inputs/password/components/password-input.tsx

resolve: #1184
Input にて、focusin, focusout が継承されない事象の修正を行った。
コンポーネントについて、以下のコンポーネントが対象
- Text Input (Vue のみ)
- Password (Vue, React)

(Vue, React) base-inputを内部で使っているコンポーネントから、ComponentProps<"input">のプロパティを公開する 

---

.changeset/quiet-turtles-tap.md
packages/wiz-ui-next/src/components/base/tooltip/tooltip.stories.ts
packages/wiz-ui-next/src/components/base/tooltip/tooltip.vue
packages/wiz-ui-react/src/components/base/tooltip/components/tooltip.tsx
packages/wiz-ui-react/src/components/base/tooltip/stories/tooltip.stories.tsx

resolve: #1188 
- vue で、expand が適用されないバグの修正
- React で、expand 機能が未実装だったため、新規で機能追加した

Bug(tooltip): Expandを指定しても横幅が横いっぱいまで広がらない 

---

.changeset/quiet-sheep-jump.md
packages/wiz-ui-next/src/components/base/popup/popup.vue
packages/wiz-ui-next/src/components/base/popup/provider.ts
packages/wiz-ui-react/src/components/base/popup/components/popup.tsx
packages/wiz-ui-react/src/components/base/popup/utils/popup-position.ts

resolve: #1100 
safari の場合のみ、ピンチズーム時に `position: fixed` な要素の `getBoundingClientRect()` で得られる座標がずれる（safari のバグ）
https://bugs.webkit.org/show_bug.cgi?id=207089
`window.visualViewport` の値を加味して座標を補正する

fix: popupの座標計算でvisualViewportを加味するように修正

---

.changeset/yellow-weeks-march.md
packages/styles/bases/search-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui-next/src/components/base/inputs/search-input/search-popup.vue
packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-popup-panel.tsx

resolve: #1210
- Search Input の Item の line-height を無効
- 無効化したことで、高さが変わった Item の調整

Bug(search-input): チェックボックスの位置を調整

---

.changeset/old-socks-cheat.md
packages/styles/bases/text.css.ts

resolve: #1259 
- DummyText にて、 user-select: none を適用した

Feat(wiz-text): blurがかかったときにuser-select: noneを有効にする

---

.changeset/silly-walls-shave.md
packages/wiz-ui-next/src/components/base/inputs/search-selector/levenshtein-distance.ts
packages/wiz-ui-next/src/components/base/inputs/search-selector/search-selector.stories.ts
packages/wiz-ui-next/src/components/base/inputs/search-selector/search-selector.vue

fix(search-input, vue): 検索改善

---

.changeset/sixty-rocks-sin.md
packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui-next/src/components/base/inputs/search-input/search-popup.vue
packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-popup-panel.tsx

Feat(search-input): ラベル位置を揃える

---

.changeset/thirty-taxis-search.md
packages/wiz-ui-react/src/components/base/anchor/components/anchor.tsx
packages/wiz-ui-react/src/components/base/anchor/stories/anchor.stories.tsx

Feat(anchor): hrefを任意プロパティに変更する

---

.changeset/sour-flies-smoke.md
packages/styles/customs/form-control.css.ts
packages/wiz-ui-next/src/components/custom/form/control.stories.ts
packages/wiz-ui-next/src/components/custom/form/control.vue
packages/wiz-ui-next/src/components/custom/form/group.stories.ts
packages/wiz-ui-react/src/components/custom/form/components/form-control.tsx
packages/wiz-ui-react/src/components/custom/form/stories/form-control.stories.tsx
packages/wiz-ui-react/src/components/custom/form/stories/form-group.stories.tsx

resolve: #1443
1. borderLeftプロパティと、borderColorプロパティの追加を行いました。
2. Figmaのスタイルに準拠するため親要素gapをxs2からxsに変更しました。(BorderとTextの幅と揃える）
認)
- h4タグの対応
- .changeset/sour-flies-smoke.md
- font-weightはコンポーネントの状態がわかりやすくなるようにWizTextのboldプロパティを用いましたが、lineHeightに関してはFontSizeによって柔軟に変更したいので `%`で指定したいと考えてlineHeightプロパティは使用しておりません。

FormControlにborderLeftプロパティと、borderColorプロパティを追加

---

.changeset/modern-kiwis-thank.md
packages/wiz-ui-next/src/components/custom/form/control.stories.ts
packages/wiz-ui-next/src/components/custom/form/control.vue
packages/wiz-ui-next/src/components/custom/form/group.stories.ts
packages/wiz-ui-next/src/components/custom/form/group.vue
packages/wiz-ui-next/src/hooks/use-form-group-provider.ts
packages/wiz-ui-react/src/components/custom/form/components/form-control.tsx
packages/wiz-ui-react/src/components/custom/form/components/form-group-context.ts
packages/wiz-ui-react/src/components/custom/form/components/form-group.tsx
packages/wiz-ui-react/src/components/custom/form/stories/form-control.stories.tsx
packages/wiz-ui-react/src/components/custom/form/stories/form-group.stories.tsx

resolve: #1446
要件にありませんでしたが、FormControl単体で使用する可能性も今後あると思ったので対応しています。
FormControlとFormGroup両方にlabelTagPositionが指定されている場合は、FormControlの設定が優先されます。

FormControl 内のラベルタグの位置を指定できるようにする

---

.github/workflows/visual-regression-test.yml

VRTの際にFontでDiffが出る問題解決のための調査ログを表示するPR
再現できないので
いつか問題が発生した日にCIをre-runしてログを取ってみる。
Mainにマージするほど望みがありそうにないので一旦PRに留める

マージしない: VRTでFontの差分が出る現象の調査

---

.changeset/moody-paws-double.md
packages/styles/bases/date-range-picker.css.ts
packages/styles/bases/password-input.css.ts
packages/styles/bases/text-input.css.ts
packages/wiz-ui-next/src/components/base/inputs/base/base.vue
packages/wiz-ui-next/src/components/base/inputs/date-range-picker/date-range-picker.vue
packages/wiz-ui-next/src/components/base/inputs/password/password.vue
packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
packages/wiz-ui-next/src/components/base/inputs/search-selector/search-selector.vue
packages/wiz-ui-next/src/components/base/inputs/selectbox/selectbox.vue
packages/wiz-ui-next/src/components/base/inputs/text/text.vue
packages/wiz-ui-react/src/components/base/inputs/base/components/base-input.tsx
packages/wiz-ui-react/src/components/base/inputs/date-range-picker/components/date-range-picker.tsx
packages/wiz-ui-react/src/components/base/inputs/password/components/password-input.tsx
packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-input.tsx
packages/wiz-ui-react/src/components/base/inputs/search-selector/components/search-selector.tsx
packages/wiz-ui-react/src/components/base/inputs/selectbox/components/selectbox.tsx
packages/wiz-ui-react/src/components/base/inputs/text/components/text-input.tsx

resolve: #1441
- inputs内でwidth propertyを使って自由に横幅を決めることができる
- 既にwidthで対応可能なComponentに関しても、expandは非推奨に
- widthを追加したComponentはこれまで通りexpandの設定を優先し動作が変わらないこと

 feat(input): widthプロパティを使用可能にして、expandを非推奨にする

---

.changeset/perfect-ghosts-scream.md
packages/wiz-ui-react/src/components/base/accordion/components/accordion.tsx
packages/wiz-ui-react/src/components/base/dropdown/components/dropdown-item.tsx
packages/wiz-ui-react/src/components/base/inputs/toggle-switch/components/toggle-switch.tsx
packages/wiz-ui-react/src/components/base/navigation/components/navigation-item.tsx
packages/wiz-ui-react/src/components/base/pagination/components/pagination.tsx
packages/wiz-ui-react/src/components/base/panel-switch/components/panel-switch.tsx
packages/wiz-ui-react/src/components/base/show-more-less/components/show-more-less.tsx
packages/wiz-ui-react/src/components/base/tab/components/tab.tsx
packages/wiz-ui-react/src/components/base/text-area/components/text-area.tsx
packages/wiz-ui-react/src/components/custom/chat/components/chat-card.tsx

resolve: #1218
E2Eテストのためdata-testidをComponentに付与できるようにするために、Wrapperにその属性の取りうる値をpropsで渡せるようにしました。
どこにつけるかは、Issuesでまとめており何も書いてないのはWrapperにつけるということで合意が取れております。
- シンプルに親要素につけるだけのものを対応しました（anchorは別対応します)
https://github.com/Wizleap-Inc/wiz-ui/pull/1488

Feat: E2Eテストのためdata-*をComponentに付与できるようにする(一部）
